[package]
name = "keld-update-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "=0.4.13"
keld-update = { path = "..", features = ["fuzzing"] }

[[bin]]
name = "canonical_archive"
path = "fuzz_targets/canonical_archive.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
