import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const STRUCT_NAMES = ["EchoRequest", "EchoResponse"] as const;
const repositoryRoot = resolve(import.meta.dir, "../../../..");
const rustSourcePath = resolve(repositoryRoot, "crates/keld-ipc/src/echo.rs");
const generatedPaths = [
  resolve(repositoryRoot, "crates/keld-cli/templates/hello/src/echo.generated.ts"),
  resolve(repositoryRoot, "packages/@keld/api/src/echo.generated.ts"),
] as const;
const channelTableSourcePath = resolve(repositoryRoot, "crates/keld-ipc/src/channel_table.rs");
const transportPath = resolve(repositoryRoot, "packages/@keld/kipc/src/transport.ts");

type StructName = (typeof STRUCT_NAMES)[number];
type SupportedRustType = "String" | "u32";

interface RustField {
  name: string;
  rustType: SupportedRustType;
}

function fail(detail: string): never {
  throw new Error(`echo codegen: ${detail}`);
}

function parseStruct(lines: readonly string[], name: StructName): RustField[] {
  const declaration = new RegExp(`^\\s*pub\\s+struct\\s+${name}\\b`);
  const candidates = lines
    .map((line, index) => ({ line, index }))
    .filter(({ line }) => declaration.test(line));

  if (candidates.length === 0) fail(`missing public ${name} struct in crates/keld-ipc/src/echo.rs`);
  if (candidates.length !== 1) fail(`duplicate public ${name} struct declarations`);

  const [{ line: opening, index: start }] = candidates;
  if (opening !== `pub struct ${name} {`) {
    fail(`${name} must use the rustfmt-normalized named public-field form`);
  }

  const fields: RustField[] = [];
  const names = new Set<string>();
  for (let index = start + 1; index < lines.length; index += 1) {
    const line = lines[index];
    if (line === "}") {
      if (fields.length === 0) fail(`${name} must contain at least one public field`);
      return fields;
    }
    if (line.length === 0 || /^    \/\/\/(?: |$)/.test(line)) continue;

    const field = /^    pub ([A-Za-z_][A-Za-z0-9_]*): ([A-Za-z_][A-Za-z0-9_:<>]*),$/.exec(line);
    if (!field) {
      fail(`${name} contains unsupported body syntax on source line ${index + 1}: ${line.trim()}`);
    }
    const [, fieldName, rustType] = field;
    if (rustType !== "String" && rustType !== "u32") {
      fail(`${name}.${fieldName} uses unsupported Rust type ${rustType}; supported: String, u32`);
    }
    if (!names.add(fieldName)) fail(`${name} contains duplicate field ${fieldName}`);
    fields.push({ name: fieldName, rustType });
  }

  return fail(`unterminated public ${name} struct`);
}

function renderField(field: RustField): string[] {
  if (field.rustType === "String") return [`  ${field.name}: string;`];
  return [
    "  /** Rust u32 domain: integer in 0..=4_294_967_295; runtime bounds stay in the postcard codec. */",
    `  ${field.name}: number;`,
  ];
}

/** Renders the bounded echo declarations from their canonical Rust structs. */
export function renderEchoDeclarations(rustSource: string): string {
  const lines = rustSource.replaceAll("\r\n", "\n").split("\n");
  const output = [
    "// @generated by packages/@keld/kipc/scripts/echo-codegen.ts.",
    "// Source: crates/keld-ipc/src/echo.rs. Do not edit by hand.",
    "",
  ];

  for (const name of STRUCT_NAMES) {
    output.push(`export interface ${name} {`);
    for (const field of parseStruct(lines, name)) output.push(...renderField(field));
    output.push("}", "");
  }
  return output.join("\n");
}

function currentGeneratedBytes(): string {
  return renderEchoDeclarations(readFileSync(rustSourcePath, "utf8"));
}

/** Fails when checked-in bytes do not exactly match the canonical Rust source. */
export function assertEchoArtifactFresh(rustSource: string, artifact: Uint8Array): void {
  const expected = Buffer.from(renderEchoDeclarations(rustSource), "utf8");
  if (!Buffer.from(artifact).equals(expected)) {
    fail("committed echo.generated.ts is stale; run bun run echo:generate");
  }
}

// ---------------------------------------------------------------------------
// Channel-table target (GH-508 spec docs/specs/gh508-kipc-channel-table.md §4.3).
//
// Reads the Rust channel table and rewrites one delimited region of the single
// staged transport file. Rust compilation (`validate_table`) is the validator
// of record; this parser admits only the rustfmt-normalized entry forms and
// fails closed, naming the source line, on anything else. It never guesses.
// ---------------------------------------------------------------------------

/** First line of the generated region; the rest of the line is its provenance. */
export const CHANNEL_REGION_BEGIN = "// @generated-begin channel-table";
/** Last line of the generated region. */
export const CHANNEL_REGION_END = "// @generated-end channel-table";

const ENTRY_HEADER = /^pub const ([A-Z][A-Z0-9_]*): ChannelEntry =(.*)$/;
const ENTRY_NAME = /^"([a-z][a-z0-9-]{0,31})"$/;
const ENTRY_ID = /^(?:0|[1-9][0-9]{0,4})$/;
const ENTRY_CLASS = /^ReceiveClass::[A-Z][A-Za-z0-9]*$/;
const CAPABILITY_PATH = "[A-Za-z_][A-Za-z0-9_]*(?:::[A-Za-z_][A-Za-z0-9_]*)*";
const ENTRY_AUTHORITY = new RegExp(
  `^Authority::(?:HostInternal|Guarded\\(&\\[\\s*${CAPABILITY_PATH}(?:\\s*,\\s*${CAPABILITY_PATH})*\\s*,?\\s*\\]\\))$`,
);
const MAX_ENTRY_LINES = 32;

/** One parsed `pub const NAME: ChannelEntry` declaration. */
export interface ChannelTableEntry {
  /** Rust constant name, e.g. `ECHO`. */
  readonly rustName: string;
  /** Entry name, e.g. `echo`. */
  readonly name: string;
  /** Wire channel id. */
  readonly id: number;
}

/** The parsed channel table in `CHANNEL_TABLE` order. */
export interface ChannelTable {
  /** `HANDSHAKE_CHANNEL`, reserved for `HELLO`. */
  readonly handshake: number;
  readonly entries: readonly ChannelTableEntry[];
}

interface SourceArgument {
  text: string;
  line: number;
}

function channelFail(line: number, detail: string): never {
  return fail(`crates/keld-ipc/src/channel_table.rs source line ${line}: ${detail}`);
}

/** Splits call arguments at top-level commas, keeping each argument's source line. */
function splitArguments(segments: readonly SourceArgument[]): SourceArgument[] {
  const args: SourceArgument[] = [];
  let depth = 0;
  let inString = false;
  let current = "";
  let currentLine = segments[0]?.line ?? 0;
  for (const segment of segments) {
    for (let index = 0; index < segment.text.length; index += 1) {
      const char = segment.text[index];
      if (current.trim().length === 0) currentLine = segment.line;
      if (inString) {
        if (char === "\\") {
          current += char + (segment.text[index + 1] ?? "");
          index += 1;
          continue;
        }
        if (char === '"') inString = false;
      } else if (char === '"') {
        inString = true;
      } else if ("([{".includes(char)) {
        depth += 1;
      } else if (")]}".includes(char)) {
        depth -= 1;
      } else if (char === "," && depth === 0) {
        args.push({ text: current.trim(), line: currentLine });
        current = "";
        continue;
      }
      current += char;
    }
    current += " ";
  }
  if (current.trim().length !== 0) args.push({ text: current.trim(), line: currentLine });
  return args;
}

function parseEntry(
  lines: readonly string[],
  start: number,
): { entry: ChannelTableEntry; consumed: number } {
  const header = ENTRY_HEADER.exec(lines[start]);
  if (!header) {
    channelFail(start + 1, `unsupported ChannelEntry declaration: ${lines[start].trim()}`);
  }
  const [, rustName, rest] = header;
  let segments: SourceArgument[];
  let consumed: number;
  const singleLine = /^ ChannelEntry::new\((.*)\);$/.exec(rest);
  if (singleLine) {
    segments = [{ text: singleLine[1], line: start + 1 }];
    consumed = 1;
  } else if (rest === "") {
    const wrapped = /^    ChannelEntry::new\((.*)\);$/.exec(lines[start + 1] ?? "");
    if (!wrapped) {
      channelFail(start + 2, "expected the rustfmt-wrapped `    ChannelEntry::new(...);` line");
    }
    segments = [{ text: wrapped[1], line: start + 2 }];
    consumed = 2;
  } else if (rest === " ChannelEntry::new(") {
    segments = [];
    let index = start + 1;
    for (; index < lines.length && lines[index] !== ");"; index += 1) {
      if (index - start > MAX_ENTRY_LINES) channelFail(start + 1, `unterminated ${rustName} entry`);
      if (!lines[index].startsWith("    ")) {
        channelFail(index + 1, `entry argument is not rustfmt-indented: ${lines[index].trim()}`);
      }
      segments.push({ text: lines[index].trim(), line: index + 1 });
    }
    if (index >= lines.length) channelFail(start + 1, `unterminated ${rustName} entry`);
    consumed = index - start + 1;
  } else {
    return channelFail(start + 1, `unsupported ${rustName} initializer; use ChannelEntry::new(...)`);
  }

  const args = splitArguments(segments);
  if (args.length !== 4) {
    channelFail(start + 1, `${rustName} must pass exactly 4 arguments to ChannelEntry::new`);
  }
  const [nameArg, idArg, classArg, authorityArg] = args;
  const name = ENTRY_NAME.exec(nameArg.text);
  if (!name) {
    channelFail(nameArg.line, `entry name must be a "[a-z][a-z0-9-]{0,31}" string literal, found ${nameArg.text}`);
  }
  if (!ENTRY_ID.test(idArg.text) || Number(idArg.text) > 0xffff) {
    channelFail(idArg.line, `channel id must be a decimal u16 literal, found ${idArg.text}`);
  }
  if (!ENTRY_CLASS.test(classArg.text)) {
    channelFail(classArg.line, `receive class must be a ReceiveClass variant, found ${classArg.text}`);
  }
  if (!ENTRY_AUTHORITY.test(authorityArg.text)) {
    channelFail(
      authorityArg.line,
      `authority must be Authority::HostInternal or Authority::Guarded(&[<keld_guard constant>, ...]), found ${authorityArg.text}`,
    );
  }
  return { entry: { rustName, name: name[1], id: Number(idArg.text) }, consumed };
}

function parseTableList(lines: readonly string[], start: number): { names: string[]; consumed: number } {
  const singleLine = /^pub const CHANNEL_TABLE: &\[ChannelEntry\] = &\[(.*)\];$/.exec(lines[start]);
  let raw: string[];
  let consumed: number;
  if (singleLine) {
    raw = singleLine[1].split(",").map((name) => name.trim());
    consumed = 1;
  } else if (lines[start] === "pub const CHANNEL_TABLE: &[ChannelEntry] = &[") {
    raw = [];
    let index = start + 1;
    for (; index < lines.length && lines[index] !== "];"; index += 1) {
      const item = /^    ([A-Z][A-Z0-9_]*),$/.exec(lines[index]);
      if (!item) channelFail(index + 1, `unsupported CHANNEL_TABLE item: ${lines[index].trim()}`);
      raw.push(item[1]);
    }
    if (index >= lines.length) channelFail(start + 1, "unterminated CHANNEL_TABLE");
    consumed = index - start + 1;
  } else {
    return channelFail(start + 1, `unsupported CHANNEL_TABLE declaration: ${lines[start].trim()}`);
  }
  for (const name of raw) {
    if (!/^[A-Z][A-Z0-9_]*$/.test(name)) channelFail(start + 1, `CHANNEL_TABLE lists ${name}, which is not a constant name`);
  }
  return { names: raw, consumed };
}

/** TypeScript name: the entry name uppercased, `-` mapped to `_`, plus `_CHANNEL`. */
export function channelConstantName(name: string): string {
  return `${name.toUpperCase().replaceAll("-", "_")}_CHANNEL`;
}

/** Parses the production half of `crates/keld-ipc/src/channel_table.rs`. */
export function parseChannelTable(rustSource: string): ChannelTable {
  const all = rustSource.replaceAll("\r\n", "\n").split("\n");
  const testModule = all.indexOf("#[cfg(test)]");
  const lines = testModule === -1 ? all : all.slice(0, testModule);
  let handshake: number | undefined;
  const entries = new Map<string, ChannelTableEntry>();
  let listed: string[] | undefined;
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index];
    if (/^\s*\/\//.test(line)) continue;
    if (line.startsWith("pub const HANDSHAKE_CHANNEL")) {
      const parsed = /^pub const HANDSHAKE_CHANNEL: ChannelId = ChannelId\((0|[1-9][0-9]{0,4})\);$/.exec(line);
      if (!parsed || Number(parsed[1]) > 0xffff) channelFail(index + 1, `unsupported HANDSHAKE_CHANNEL: ${line.trim()}`);
      if (handshake !== undefined) channelFail(index + 1, "duplicate HANDSHAKE_CHANNEL");
      handshake = Number(parsed[1]);
    } else if (line.startsWith("pub const CHANNEL_TABLE")) {
      if (listed !== undefined) channelFail(index + 1, "duplicate CHANNEL_TABLE");
      const table = parseTableList(lines, index);
      listed = table.names;
      index += table.consumed - 1;
    } else if (/^pub const [A-Za-z0-9_]+: ChannelEntry\b/.test(line)) {
      const { entry, consumed } = parseEntry(lines, index);
      if (entries.has(entry.rustName)) channelFail(index + 1, `duplicate entry constant ${entry.rustName}`);
      entries.set(entry.rustName, entry);
      index += consumed - 1;
    } else if (line.includes("ChannelEntry::new(") || /\b(?:const|static)\s+[A-Za-z0-9_]+\s*:\s*ChannelEntry\b/.test(line)) {
      channelFail(index + 1, `ChannelEntry outside the admitted pub const form: ${line.trim()}`);
    }
  }
  if (handshake === undefined) fail("crates/keld-ipc/src/channel_table.rs: missing HANDSHAKE_CHANNEL");
  if (listed === undefined) fail("crates/keld-ipc/src/channel_table.rs: missing CHANNEL_TABLE");

  const ordered: ChannelTableEntry[] = [];
  for (const rustName of listed) {
    const entry = entries.get(rustName);
    if (!entry) fail(`CHANNEL_TABLE lists ${rustName}, which is not a parsed ChannelEntry constant`);
    if (ordered.includes(entry)) fail(`CHANNEL_TABLE lists ${rustName} more than once`);
    ordered.push(entry);
  }
  for (const rustName of entries.keys()) {
    if (!listed.includes(rustName)) fail(`ChannelEntry constant ${rustName} is not listed in CHANNEL_TABLE`);
  }
  const names = new Set<string>();
  const constants = new Set<string>(["HANDSHAKE_CHANNEL"]);
  for (const entry of ordered) {
    if (names.has(entry.name)) fail(`duplicate channel entry name ${entry.name}`);
    names.add(entry.name);
    const constant = channelConstantName(entry.name);
    if (constants.has(constant)) fail(`entry ${entry.name} would generate a duplicate ${constant}`);
    constants.add(constant);
  }
  return { handshake, entries: ordered };
}

/** Renders the generated `transport.ts` region, markers included, without a trailing newline. */
export function renderChannelTableRegion(rustSource: string): string {
  const table = parseChannelTable(rustSource);
  const lines = [
    `${CHANNEL_REGION_BEGIN}: packages/@keld/kipc/scripts/echo-codegen.ts from`,
    "// crates/keld-ipc/src/channel_table.rs. Do not edit by hand; run bun run echo:generate.",
    "/** Reserved `HELLO` channel (`keld_ipc::channel_table::HANDSHAKE_CHANNEL`). */",
    `export const HANDSHAKE_CHANNEL = ${table.handshake};`,
  ];
  for (const entry of table.entries) {
    lines.push(`/** Channel \`${entry.name}\` (\`keld_ipc::channel_table::${entry.rustName}\`). */`);
    lines.push(`export const ${channelConstantName(entry.name)} = ${entry.id};`);
  }
  lines.push(CHANNEL_REGION_END);
  return lines.join("\n");
}

/** Line bounds of the one generated region in `transportSource`. */
export function channelRegionBounds(transportSource: string): { lines: string[]; begin: number; end: number } {
  const lines = transportSource.split("\n");
  const begins = lines.flatMap((line, index) => (line.startsWith(CHANNEL_REGION_BEGIN) ? [index] : []));
  const ends = lines.flatMap((line, index) => (line.startsWith(CHANNEL_REGION_END) ? [index] : []));
  if (begins.length !== 1 || ends.length !== 1 || begins[0] > ends[0]) {
    fail(
      "transport.ts must contain exactly one channel-table region: one `// @generated-begin channel-table` line before one `// @generated-end channel-table` line",
    );
  }
  return { lines, begin: begins[0], end: ends[0] };
}

/** Replaces the generated region of `transportSource` with `region`. */
export function replaceChannelTableRegion(transportSource: string, region: string): string {
  const { lines, begin, end } = channelRegionBounds(transportSource);
  return [...lines.slice(0, begin), region, ...lines.slice(end + 1)].join("\n");
}

/** Fails when the committed region is not byte-identical to the render of the Rust table. */
export function assertChannelTableRegionFresh(rustSource: string, transportSource: string): void {
  const { lines, begin, end } = channelRegionBounds(transportSource);
  if (lines.slice(begin, end + 1).join("\n") !== renderChannelTableRegion(rustSource)) {
    fail("channel table region is stale; run bun run echo:generate");
  }
}

function generate(): void {
  const generated = currentGeneratedBytes();
  for (const path of generatedPaths) writeFileSync(path, generated, "utf8");
  const region = renderChannelTableRegion(readFileSync(channelTableSourcePath, "utf8"));
  writeFileSync(transportPath, replaceChannelTableRegion(readFileSync(transportPath, "utf8"), region), "utf8");
}

function check(): void {
  const rustSource = readFileSync(rustSourcePath, "utf8");
  for (const path of generatedPaths) {
    let actual: Buffer;
    try {
      actual = readFileSync(path);
    } catch (error) {
      fail(`cannot read ${path}: ${String(error)}; run bun run echo:generate`);
    }
    assertEchoArtifactFresh(rustSource, actual);
  }
  assertChannelTableRegionFresh(
    readFileSync(channelTableSourcePath, "utf8"),
    readFileSync(transportPath, "utf8"),
  );
}

if (import.meta.main) {
  try {
    const [command, ...extra] = process.argv.slice(2);
    if (extra.length !== 0 || (command !== "generate" && command !== "check")) {
      fail("usage: bun run scripts/echo-codegen.ts <generate|check>");
    }
    if (command === "generate") generate();
    else check();
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
