import { describe, expect, test } from "bun:test";
import { mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { relative, resolve } from "node:path";

import { assertEchoArtifactFresh, renderEchoDeclarations } from "./echo-codegen.ts";

const repositoryRoot = resolve(import.meta.dir, "../../../..");
const echoSource = readFileSync(
  resolve(repositoryRoot, "crates/keld-ipc/src/echo.rs"),
  "utf8",
);
const generatedPath = resolve(
  repositoryRoot,
  "crates/keld-cli/templates/hello/src/echo.generated.ts",
);
const adapterPath = resolve(repositoryRoot, "crates/keld-cli/templates/hello/src/kipc.ts");
const bodyPath = resolve(repositoryRoot, "crates/keld-cli/templates/hello/src/main-body.ts");
const transportPath = resolve(repositoryRoot, "packages/@keld/kipc/src/transport.ts");
const packageRoot = resolve(import.meta.dir, "..");

const expectedCurrentDeclarations = `// @generated by packages/@keld/kipc/scripts/echo-codegen.ts.
// Source: crates/keld-ipc/src/echo.rs. Do not edit by hand.

export interface EchoRequest {
  message: string;
  /** Rust u32 domain: integer in 0..=4_294_967_295; runtime bounds stay in the postcard codec. */
  count: number;
}

export interface EchoResponse {
  message: string;
  /** Rust u32 domain: integer in 0..=4_294_967_295; runtime bounds stay in the postcard codec. */
  count: number;
}
`;

function withTemporaryComposition(run: (directory: string) => void): void {
  const directory = mkdtempSync(resolve(tmpdir(), "keld-echo-codegen-"));
  try {
    writeFileSync(
      resolve(directory, "main.ts"),
      `${readFileSync(adapterPath, "utf8")}\n${readFileSync(bodyPath, "utf8")}`,
    );
    writeFileSync(resolve(directory, "kipc-transport.ts"), readFileSync(transportPath));
    run(directory);
  } finally {
    rmSync(directory, { force: true, recursive: true });
  }
}

function typecheckComposition(directory: string): ReturnType<typeof Bun.spawnSync> {
  const typeRoots = resolve(packageRoot, "node_modules/@types").replaceAll("\\", "/");
  writeFileSync(
    resolve(directory, "tsconfig.json"),
    JSON.stringify({
      compilerOptions: {
        allowImportingTsExtensions: true,
        isolatedModules: true,
        lib: ["ES2024"],
        module: "Preserve",
        moduleDetection: "force",
        moduleResolution: "Bundler",
        noEmit: true,
        strict: true,
        target: "ES2024",
        typeRoots: [typeRoots],
        types: ["bun"],
      },
      include: ["*.ts"],
    }),
  );
  return Bun.spawnSync(
    [process.execPath, "run", "tsc", "--project", resolve(directory, "tsconfig.json")],
    { cwd: packageRoot, env: process.env },
  );
}

interface TypeScriptSource {
  path: string;
  source: string;
}

function productionTypeScriptSources(root: string): TypeScriptSource[] {
  const sources: TypeScriptSource[] = [];
  const visit = (directory: string): void => {
    for (const entry of readdirSync(directory, { withFileTypes: true })) {
      if (entry.name === "node_modules") continue;
      const path = resolve(directory, entry.name);
      if (entry.isDirectory()) {
        visit(path);
      } else if (
        entry.isFile() &&
        entry.name.endsWith(".ts") &&
        !entry.name.endsWith(".test.ts") &&
        path !== generatedPath
      ) {
        sources.push({ path: relative(repositoryRoot, path), source: readFileSync(path, "utf8") });
      }
    }
  };
  visit(root);
  return sources;
}

function assertNoHandWrittenEchoPayload(sources: readonly TypeScriptSource[]): void {
  for (const candidate of sources) {
    expect(candidate.source, candidate.path).not.toMatch(
      /\b(?:export\s+)?(?:interface|type)\s+Echo(?:Request|Response)\b/,
    );
  }
}

describe("echo declaration generator", () => {
  test("renders current Rust-owned declarations deterministically", () => {
    const first = renderEchoDeclarations(echoSource);
    const second = renderEchoDeclarations(echoSource);
    expect(first).toBe(second);
    expect(first).toBe(expectedCurrentDeclarations);
  });

  test("supported Rust field changes deterministically change the output", () => {
    const renamed = echoSource.replaceAll("pub count: u32,", "pub attempts: u32,");
    const added = echoSource.replace(
      "pub message: String,\n    /// Repeat count metadata",
      "pub message: String,\n    pub label: String,\n    /// Repeat count metadata",
    );
    const typeChanged = echoSource.replaceAll("pub count: u32,", "pub count: String,");

    expect(renderEchoDeclarations(renamed)).toContain("attempts: number;");
    expect(renderEchoDeclarations(renamed)).not.toContain("count: number;");
    expect(renderEchoDeclarations(added)).toContain("label: string;");
    expect(renderEchoDeclarations(typeChanged)).toContain("count: string;");
    expect(renderEchoDeclarations(typeChanged)).not.toContain("Rust u32 domain");
    expect(renderEchoDeclarations(renamed)).not.toBe(expectedCurrentDeclarations);
    expect(renderEchoDeclarations(added)).not.toBe(expectedCurrentDeclarations);
    expect(renderEchoDeclarations(typeChanged)).not.toBe(expectedCurrentDeclarations);
  });

  test("committed bytes are fresh and stale or hand-edited bytes fail", () => {
    const committed = readFileSync(generatedPath);
    expect(() => assertEchoArtifactFresh(echoSource, committed)).not.toThrow();
    expect(() => assertEchoArtifactFresh(echoSource, Buffer.concat([committed, Buffer.from("// edit\n")]))).toThrow(
      "stale",
    );
    const renamed = echoSource.replaceAll("pub count: u32,", "pub attempts: u32,");
    expect(() => assertEchoArtifactFresh(renamed, committed)).toThrow("stale");
  });

  test("admits rustfmt field docs but rejects unsupported or lossy shapes", () => {
    expect(() => renderEchoDeclarations(echoSource)).not.toThrow();

    const unsupported = [
      ["unsupported type", echoSource.replace("pub count: u32,", "pub count: u64,")],
      [
        "field attribute",
        echoSource.replace("    pub count: u32,", "    #[serde(default)]\n    pub count: u32,"),
      ],
      ["private field", echoSource.replace("pub count: u32,", "count: u32,")],
      ["malformed field", echoSource.replace("pub count: u32,", "pub count: u32")],
      [
        "tuple struct",
        echoSource.replace(
          "pub struct EchoRequest {\n    /// Message to echo back.\n    pub message: String,\n    /// Repeat count metadata (demonstrates structured fields).\n    pub count: u32,\n}",
          "pub struct EchoRequest(pub String, pub u32);",
        ),
      ],
      ["generic struct", echoSource.replace("pub struct EchoRequest {", "pub struct EchoRequest<T> {")],
      [
        "arbitrary body line",
        echoSource.replace("    pub count: u32,", "    const BAD: u32 = 1;\n    pub count: u32,"),
      ],
    ] as const;

    for (const [label, source] of unsupported) {
      expect(() => renderEchoDeclarations(source), label).toThrow(/echo codegen:/);
    }
  });

  test("requires exactly one named request and response struct", () => {
    expect(() => renderEchoDeclarations(echoSource.replace("EchoRequest", "MissingRequest"))).toThrow(
      "EchoRequest",
    );
    expect(() => renderEchoDeclarations(`${echoSource}\n${echoSource}`)).toThrow("duplicate");
  });

  test("generated declarations are the sole payload owner and stay type-only", () => {
    const generated = readFileSync(generatedPath, "utf8");
    const adapter = readFileSync(adapterPath, "utf8");

    const assertOwnership = (candidate: string): void => {
      expect(candidate).toContain(
        'import type { EchoRequest, EchoResponse } from "./echo.generated.ts";',
      );
      expect(candidate).toContain(
        'export type { EchoRequest, EchoResponse } from "./echo.generated.ts";',
      );
      expect(candidate).not.toMatch(/(?:interface|type)\s+Echo(?:Request|Response)\b/);
      expect(candidate).toContain(
        "async echo(request: EchoRequest): Promise<EchoResponse>",
      );
    };

    assertOwnership(adapter);
    expect(generated.match(/export interface EchoRequest\b/g)).toHaveLength(1);
    expect(generated.match(/export interface EchoResponse\b/g)).toHaveLength(1);
    expect(generated).not.toContain("EchoClient");
    expect(generated).not.toMatch(/^export (?:const|class|function)\b/m);

    const productionSources = [
      ...productionTypeScriptSources(resolve(repositoryRoot, "crates")),
      ...productionTypeScriptSources(resolve(repositoryRoot, "packages")),
    ];
    assertNoHandWrittenEchoPayload(productionSources);

    const localDeclaration = `${adapter}\ninterface EchoRequest { message: string; count: number }\n`;
    expect(() => assertOwnership(localDeclaration)).toThrow();
    const transportDeclaration = productionSources.map((candidate) =>
      candidate.path.replaceAll("\\", "/") === "packages/@keld/kipc/src/transport.ts"
        ? {
            ...candidate,
            source: `${candidate.source}\nexport interface EchoRequest { message: string; count: number }\n`,
          }
        : candidate,
    );
    expect(() => assertNoHandWrittenEchoPayload(transportDeclaration)).toThrow();
  });

  test("exact shipping composition typechecks and a generated rename exposes stale production use", () => {
    withTemporaryComposition((directory) => {
      writeFileSync(resolve(directory, "echo.generated.ts"), renderEchoDeclarations(echoSource));
      const baseline = typecheckComposition(directory);
      expect(new TextDecoder().decode(baseline.stderr)).toBe("");
      expect(baseline.exitCode).toBe(0);

      const renamed = echoSource.replaceAll("pub count: u32,", "pub attempts: u32,");
      writeFileSync(resolve(directory, "echo.generated.ts"), renderEchoDeclarations(renamed));
      const drift = typecheckComposition(directory);
      const diagnostic = new TextDecoder().decode(drift.stdout) + new TextDecoder().decode(drift.stderr);
      expect(drift.exitCode).not.toBe(0);
      expect(diagnostic).toContain("count");
      expect(diagnostic).toContain("EchoRequest");
    });
  });

  test("type-only generated file stays out of runtime staging and a value edge fails resolution", () => {
    withTemporaryComposition((directory) => {
      const environment = { ...process.env };
      delete environment.KELD_APP_LINK;
      const baseline = Bun.spawnSync([process.execPath, "run", resolve(directory, "main.ts")], {
        cwd: directory,
        env: environment,
      });
      const baselineOutput =
        new TextDecoder().decode(baseline.stdout) + new TextDecoder().decode(baseline.stderr);
      expect(baseline.exitCode).toBe(1);
      expect(baselineOutput).toContain("KELD-CLI-010");
      expect(baselineOutput).not.toContain("echo.generated.ts");

      const mainPath = resolve(directory, "main.ts");
      const valueUse = readFileSync(mainPath, "utf8")
        .replace(
          'import type { EchoRequest, EchoResponse } from "./echo.generated.ts";',
          'import { EchoRequest, type EchoResponse } from "./echo.generated.ts";\nvoid EchoRequest;',
        );
      writeFileSync(mainPath, valueUse);
      const mutation = Bun.spawnSync([process.execPath, "run", mainPath], {
        cwd: directory,
        env: environment,
      });
      const mutationOutput =
        new TextDecoder().decode(mutation.stdout) + new TextDecoder().decode(mutation.stderr);
      expect(mutation.exitCode).not.toBe(0);
      expect(mutationOutput).toContain("echo.generated.ts");
      expect(mutationOutput).not.toContain("KELD-CLI-010");
    });
  });
});
