import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const STRUCT_NAMES = ["EchoRequest", "EchoResponse"] as const;
const repositoryRoot = resolve(import.meta.dir, "../../../..");
const rustSourcePath = resolve(repositoryRoot, "crates/keld-ipc/src/echo.rs");
const generatedPath = resolve(
  repositoryRoot,
  "crates/keld-cli/templates/hello/src/echo.generated.ts",
);

type StructName = (typeof STRUCT_NAMES)[number];
type SupportedRustType = "String" | "u32";

interface RustField {
  name: string;
  rustType: SupportedRustType;
}

function fail(detail: string): never {
  throw new Error(`echo codegen: ${detail}`);
}

function parseStruct(lines: readonly string[], name: StructName): RustField[] {
  const declaration = new RegExp(`^\\s*pub\\s+struct\\s+${name}\\b`);
  const candidates = lines
    .map((line, index) => ({ line, index }))
    .filter(({ line }) => declaration.test(line));

  if (candidates.length === 0) fail(`missing public ${name} struct in crates/keld-ipc/src/echo.rs`);
  if (candidates.length !== 1) fail(`duplicate public ${name} struct declarations`);

  const [{ line: opening, index: start }] = candidates;
  if (opening !== `pub struct ${name} {`) {
    fail(`${name} must use the rustfmt-normalized named public-field form`);
  }

  const fields: RustField[] = [];
  const names = new Set<string>();
  for (let index = start + 1; index < lines.length; index += 1) {
    const line = lines[index];
    if (line === "}") {
      if (fields.length === 0) fail(`${name} must contain at least one public field`);
      return fields;
    }
    if (line.length === 0 || /^    \/\/\/(?: |$)/.test(line)) continue;

    const field = /^    pub ([A-Za-z_][A-Za-z0-9_]*): ([A-Za-z_][A-Za-z0-9_:<>]*),$/.exec(line);
    if (!field) {
      fail(`${name} contains unsupported body syntax on source line ${index + 1}: ${line.trim()}`);
    }
    const [, fieldName, rustType] = field;
    if (rustType !== "String" && rustType !== "u32") {
      fail(`${name}.${fieldName} uses unsupported Rust type ${rustType}; supported: String, u32`);
    }
    if (!names.add(fieldName)) fail(`${name} contains duplicate field ${fieldName}`);
    fields.push({ name: fieldName, rustType });
  }

  return fail(`unterminated public ${name} struct`);
}

function renderField(field: RustField): string[] {
  if (field.rustType === "String") return [`  ${field.name}: string;`];
  return [
    "  /** Rust u32 domain: integer in 0..=4_294_967_295; runtime bounds stay in the postcard codec. */",
    `  ${field.name}: number;`,
  ];
}

/** Renders the bounded echo declarations from their canonical Rust structs. */
export function renderEchoDeclarations(rustSource: string): string {
  const lines = rustSource.replaceAll("\r\n", "\n").split("\n");
  const output = [
    "// @generated by packages/@keld/kipc/scripts/echo-codegen.ts.",
    "// Source: crates/keld-ipc/src/echo.rs. Do not edit by hand.",
    "",
  ];

  for (const name of STRUCT_NAMES) {
    output.push(`export interface ${name} {`);
    for (const field of parseStruct(lines, name)) output.push(...renderField(field));
    output.push("}", "");
  }
  return output.join("\n");
}

function currentGeneratedBytes(): string {
  return renderEchoDeclarations(readFileSync(rustSourcePath, "utf8"));
}

/** Fails when checked-in bytes do not exactly match the canonical Rust source. */
export function assertEchoArtifactFresh(rustSource: string, artifact: Uint8Array): void {
  const expected = Buffer.from(renderEchoDeclarations(rustSource), "utf8");
  if (!Buffer.from(artifact).equals(expected)) {
    fail("committed echo.generated.ts is stale; run bun run echo:generate");
  }
}

function generate(): void {
  writeFileSync(generatedPath, currentGeneratedBytes(), "utf8");
}

function check(): void {
  let actual: Buffer;
  try {
    actual = readFileSync(generatedPath);
  } catch (error) {
    fail(`cannot read ${generatedPath}: ${String(error)}; run bun run echo:generate`);
  }
  assertEchoArtifactFresh(readFileSync(rustSourcePath, "utf8"), actual);
}

if (import.meta.main) {
  try {
    const [command, ...extra] = process.argv.slice(2);
    if (extra.length !== 0 || (command !== "generate" && command !== "check")) {
      fail("usage: bun run scripts/echo-codegen.ts <generate|check>");
    }
    if (command === "generate") generate();
    else check();
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
