// Builds trace_summary.md from trace*.jsonl + run-result*.json (+ hand-written summary-notes.md).
// Run WITHOUT the preload:  bun --no-install harness/summarize.mjs
import fs from 'node:fs';
import path from 'node:path';

const P3 = path.resolve(import.meta.dir, '..');
const PHASES = ['import', 'boot', 'open', 'save', 'close'];
const KINDS = ['electron', 'fs', 'child_process', 'net', 'env', 'os'];

function load(suffix) {
	const tp = path.join(P3, 'trace' + suffix + '.jsonl');
	if (!fs.existsSync(tp)) return null;
	const events = fs.readFileSync(tp, 'utf8').split('\n').filter(Boolean).map((l) => JSON.parse(l));
	const rp = path.join(P3, 'harness', 'run-result' + suffix + '.json');
	const result = fs.existsSync(rp) ? JSON.parse(fs.readFileSync(rp, 'utf8')) : null;
	return { suffix, events, result };
}
const primary = load('');
const variant = load('.unpackaged');
if (!primary) throw new Error('no trace.jsonl; run harness/run.sh first');

const isCanary = (e) => e.step === 'canary';
const isDriver = (e) => e.driver === true;
const isErr = (e) => e.ev === 'err';
const isAuthority = (e) => !isCanary(e) && !isDriver(e) && !isErr(e);

const md = [];
const out = (s = '') => md.push(s);
const esc = (s) => String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
const short = (v, n = 110) => { const s = typeof v === 'string' ? v : JSON.stringify(v); return s.length > n ? s.slice(0, n - 1) + '...' : s; };

function norm(p) {
	if (p == null) return '';
	return String(p)
		.replace(/config\.json\.tmp-[0-9a-f]+/g, 'config.json.tmp-*')
		.replace(/\.drawio-bkp-[0-9a-f-]{36}\.tmp/g, '.drawio-bkp-<uuid>.tmp')
		.replace(/fd:\d+\(/g, 'fd(');
}
function callerOf(e) { return e.caller ? e.caller.replace(/^src\/main\//, '') : (e.via ? 'via ' + e.via.replace(/^pkg:/, '') : (e.internal ? '(runtime)' : '-')); }

function countTable(events) {
	const c = {};
	for (const e of events) {
		if (!isAuthority(e)) continue;
		c[e.phase] = c[e.phase] || {};
		c[e.phase][e.kind] = (c[e.phase][e.kind] || 0) + 1;
	}
	return c;
}

// ---------------------------------------------------------------------------
out('# draw.io Electron main under Bun 1.4.2: boot-and-authority trace');
out();
out('Generated by `harness/summarize.mjs` from `trace.jsonl` (packaged-like run) and `trace.unpackaged.jsonl` (dev-tree run). Path prefixes: `<APP>` = `p3/drawio-desktop`, `<HOME>` = `p3/fakehome`, `<P3>` = the experiment root. Everything was written under `p3/`; no network was available to the app (every outbound attempt is refused by the harness and recorded as `kind:"net"`).');
out();

// ---- 1. outcome -------------------------------------------------------------
const rr = primary.result;
out('## 1. Did each phase complete?');
out();
if (rr) {
	const byPhase = {};
	for (const s of rr.steps) { (byPhase[s.phase] = byPhase[s.phase] || []).push(s); }
	out('| phase | steps passed | steps failed | result |');
	out('|---|---|---|---|');
	for (const ph of PHASES) {
		const st = byPhase[ph] || [];
		const ok = st.filter((s) => s.ok).length;
		out(`| ${ph} | ${ok} | ${st.length - ok} | ${st.length && ok === st.length ? 'completed' : (st.length ? 'INCOMPLETE' : 'not reached')} |`);
	}
	out();
	out('Step-by-step (packaged-like run):');
	out();
	out('| phase | step | ok | detail |');
	out('|---|---|---|---|');
	for (const s of rr.steps) out(`| ${s.phase} | ${esc(s.step)} | ${s.ok ? 'yes' : '**NO**'} | ${esc(short(s.detail === null ? '' : s.detail, 120))} |`);
	out();
	out(`Import error: ${rr.importError ? '`' + rr.importError.message + '`' : 'none (module graph evaluated; no top-level-await failure)'}. Fatal runner error: ${rr.fatal ? rr.fatal.message : 'none'}.`);
}
out();

// ---- 2. counts ----------------------------------------------------------------
out('## 2. Event counts (authority events only: excludes driver markers, `:error` follow-ups and the harness canary)');
out();
for (const run of [primary, variant].filter(Boolean)) {
	const c = countTable(run.events);
	const title = run.suffix === '' ? 'Primary: `trace.jsonl` (app.isPackaged=true, as shipped)' : 'Variant: `trace.unpackaged.jsonl` (app.isPackaged=false, raw dev tree)';
	out(`**${title}**`);
	out();
	out('| phase | ' + KINDS.join(' | ') + ' | total |');
	out('|---|' + KINDS.map(() => '---:').join('|') + '|---:|');
	const tot = {};
	for (const ph of PHASES) {
		let row = 0;
		const cells = KINDS.map((k) => { const n = (c[ph] && c[ph][k]) || 0; tot[k] = (tot[k] || 0) + n; row += n; return n; });
		out(`| ${ph} | ${cells.join(' | ')} | ${row} |`);
	}
	out(`| **all** | ${KINDS.map((k) => tot[k] || 0).join(' | ')} | ${KINDS.reduce((a, k) => a + (tot[k] || 0), 0)} |`);
	out();
	const ops = {};
	for (const e of run.events) if (isAuthority(e) && e.kind === 'electron') ops[e.op || 'call'] = (ops[e.op || 'call'] || 0) + 1;
	const drv = run.events.filter(isDriver).length, errs = run.events.filter(isErr).length, can = run.events.filter(isCanary).length;
	out(`Electron events by op: ${Object.entries(ops).map(([k, v]) => k + '=' + v).join(', ')}. Not counted above: ${drv} driver markers, ${errs} \`:error\` follow-ups, ${can} canary events. File has ${run.events.length} lines total.`);
	out();
}

// ---- 3. electron members before the first BrowserWindow -----------------------------
out('## 3. Electron members touched before the first `new BrowserWindow`');
out();
{
	const ev = primary.events;
	const firstWin = ev.find((e) => e.kind === 'electron' && e.member_or_op === 'BrowserWindow' && e.op === 'new');
	const cutoff = firstWin ? firstWin.seq : Infinity;
	out(`First window construction is trace seq **${firstWin ? firstWin.seq : 'n/a'}** (phase ${firstWin ? firstWin.phase : '-'}; the app creates it with default \`show:true\`, so this is the "would show its first window" moment). Members in order of first touch, with every op seen and how often (the bracketed op is the first one):`);
	out();
	out('| # | first seq | phase | member | ops (count) | args (first call; for on/once/handle: every event name) | first caller |');
	out('|---:|---:|---|---|---|---|---|');
	const seen = new Map();
	for (const e of ev) {
		if (e.seq >= cutoff) break;
		if (e.kind !== 'electron' || !isAuthority(e)) continue;
		const k = e.member_or_op;
		if (!seen.has(k)) seen.set(k, { first: e, ops: {}, names: [] });
		const r = seen.get(k);
		if (/\.(on|once|handle|handleOnce)$/.test(k) && Array.isArray(e.args_shape) && typeof e.args_shape[0] === 'string' && !r.names.includes(e.args_shape[0])) r.names.push(e.args_shape[0]);
		const o = (e.op || 'call') + (e.fn_ref ? '(ref)' : '') + (e.unresolved ? '(UNRESOLVED)' : '');
		r.ops[o] = (r.ops[o] || 0) + 1;
	}
	let i = 0;
	for (const [m, r] of seen) {
		const argsCell = r.names.length ? r.names.join(', ') : (r.first.args_shape === null ? (r.first.value_shape !== undefined ? '= ' + short(r.first.value_shape, 40) : '') : short(r.first.args_shape, 60));
		out(`| ${++i} | ${r.first.seq} | ${r.first.phase} | \`${m}\` | ${Object.entries(r.ops).map(([a, b]) => a + ' x' + b).join(', ')} | ${esc(argsCell)} | ${esc(callerOf(r.first))} |`);
	}
	out();
	const libOnly = [...seen.values()].filter((r) => !r.first.caller).length;
	out(`${seen.size} distinct members. ${libOnly} of them were first touched by a dependency (electron-log, electron-store, electron-updater, electron-context-menu, electron-is-dev) rather than by \`src/main\`; \`caller\` is the first \`src/main\` frame on the stack, \`via\` the innermost non-harness frame when it is a dependency.`);
}
out();

// ---- 3b. IPC surface -----------------------------------------------------------------------------------------
out('## 3b. IPC and event surface the main process registers');
out();
{
	const ev = primary.events.filter(isAuthority);
	const chans = new Map();
	for (const e of ev) {
		const m = /^ipcMain\.(on|once|handle|handleOnce)$/.exec(e.member_or_op);
		if (!m || !Array.isArray(e.args_shape)) continue;
		const ch = String(e.args_shape[0]);
		const owner = e.via ? e.via.replace(/^pkg:/, '').split('/')[0] : (e.caller ? 'src/main' : '?'); // registering code (via) wins over the initiator (caller)
		const k = ch + '\u0001' + m[1];
		if (!chans.has(k)) chans.set(k, { ch, kind: m[1], owner, phase: e.phase, seq: e.seq, n: 0 });
		chans.get(k).n++;
	}
	out('Every `ipcMain.on/once/handle` registration (these are the renderer-reachable entry points; note the owner: dependencies register channels too):');
	out();
	out('| seq | phase | channel | kind | registered by | n |');
	out('|---:|---|---|---|---|---:|');
	for (const r of chans.values()) out(`| ${r.seq} | ${r.phase} | \`${r.ch}\` | ${r.kind} | ${r.owner}${r.owner === 'src/main' ? '' : ' (library)'} | ${r.n} |`);
	out();
	const appOn = new Map();
	for (const e of ev) {
		if (!/^(app)\.(on|once)$/.test(e.member_or_op) || !Array.isArray(e.args_shape)) continue;
		const k = String(e.args_shape[0]);
		if (!appOn.has(k)) appOn.set(k, { phase: e.phase, owner: e.via ? e.via.replace(/^pkg:/, '').split('/')[0] : (e.caller ? 'src/main' : '?') });
	}
	out('`app.on/once` events subscribed: ' + [...appOn.entries()].map(([k, v]) => '`' + k + '` (' + v.owner + ', ' + v.phase + ')').join(', ') + '.');
	out();
	// rendererReq actions: static list from source, exercised list from driver markers
	const srcPath = path.join(P3, 'drawio-desktop', 'src', 'main', 'electron.js');
	const src = fs.readFileSync(srcPath, 'utf8');
	const start = src.indexOf('switch(args.action)');
	const endIdx = src.indexOf('\n\t\t};', start);
	const block = src.slice(start, endIdx);
	const actions = [...block.matchAll(/case '([A-Za-z]+)':/g)].map((m) => m[1]);
	const klass = {
		saveFile: 'fs write (+backup, verify re-read)', writeFile: 'fs write', saveDraft: 'fs write (sibling .dtmp)', getFileDrafts: 'fs read/stat (+legacy draft rename)',
		getBkpFile: 'fs read', getDocumentsFolder: 'app.getPath', checkFileExists: 'fs stat', showOpenDialog: 'dialog + bless path', showSaveDialog: 'dialog + bless path',
		isPluginsEnabled: 'none', dirname: 'none (pure path.dirname)', readFile: 'fs read', clipboardAction: 'clipboard', deleteFile: 'fs unlink (content-sniffed)',
		fileStat: 'fs stat', isFileWritable: 'fs access', windowAction: 'window control', openExternal: 'shell.openExternal (http/https/mailto/tel/callto)',
		watchFile: 'fs.watchFile poll', unwatchFile: 'fs.unwatchFile', exit: 'app.quit', getLocalFonts: 'child_process execFile (fc-list / powershell)', isFullscreen: 'window query',
	};
	const exercised = new Set();
	for (const e of primary.events) if (e.driver && e.member_or_op === '<driver> ipc:rendererReq' && e.args_shape && e.args_shape.action) exercised.add(e.args_shape.action);
	out(`\`rendererReq\` action switch (static, from src/main/electron.js): ${actions.length} actions; ${[...exercised].filter((a) => actions.includes(a)).length} exercised in this run.`);
	out();
	out('| action | authority behind it | exercised here |');
	out('|---|---|---|');
	for (const a of actions) out(`| \`${a}\` | ${klass[a] || '?'} | ${exercised.has(a) ? 'yes' : 'no'} |`);
	out();
}

// ---- 4. authority ops by phase ----------------------------------------------------------
out('## 4. Every authority op, grouped by phase');
out();
out('fs/child_process/net/os rows are grouped by (kind, op, target) and show repeat count, first seq and the first `src/main` caller. env is listed as variable names read (values are never recorded). Electron API calls are summarised per phase in section 4b. A caller of `-` means no `src/main` frame was on the JS stack (async continuation inside a dependency, or runtime-internal).');
out();
function groupRows(events, kind) {
	const g = new Map();
	for (const e of events) {
		if (!isAuthority(e) || e.kind !== kind) continue;
		const target = norm(e.path || e.host || e.cmd || '');
		const key = [e.phase, e.member_or_op, target, e.access || '', e.blocked || ''].join('\u0001');
		if (!g.has(key)) g.set(key, { e, n: 0, target });
		g.get(key).n++;
	}
	return g;
}
for (const ph of PHASES) {
	out(`### Phase \`${ph}\``);
	out();
	for (const kind of ['fs', 'child_process', 'net', 'os']) {
		const g = groupRows(primary.events.filter((e) => e.phase === ph), kind);
		if (!g.size) { out(`- ${kind}: none`); continue; }
		out(`- **${kind}** (${[...g.values()].reduce((a, r) => a + r.n, 0)} events, ${g.size} distinct)`);
		out();
		out('| first seq | op | access | target | n | caller | note |');
		out('|---:|---|---|---|---:|---|---|');
		for (const r of g.values()) {
			const e = r.e;
			const note = e.blocked ? 'BLOCKED ' + e.blocked : (e.method ? e.method : '');
			out(`| ${e.seq} | \`${e.member_or_op}\` | ${e.access || ''} | ${esc(short(r.target, 100))} | ${r.n} | ${esc(callerOf(e))} | ${note} |`);
		}
		out();
	}
	const envNames = new Map();
	for (const e of primary.events) {
		if (!isAuthority(e) || e.kind !== 'env' || e.phase !== ph) continue;
		const k = e.member_or_op.replace('env.', '') + ' ' + (typeof e.args_shape === 'string' ? e.args_shape : JSON.stringify(e.args_shape));
		if (!envNames.has(k)) envNames.set(k, { n: 0, e });
		envNames.get(k).n++;
	}
	out(`- **env** (${[...envNames.values()].reduce((a, r) => a + r.n, 0)} events): ` + (envNames.size ? [...envNames.entries()].map(([k, r]) => '`' + k + '`' + (r.n > 1 ? ' x' + r.n : '') + ' (' + callerOf(r.e).replace(/^via /, '') + ')').join('; ') : 'none'));
	out();
}

out('### 4b. Electron API surface by phase (distinct members; counts of get/call/new/set)');
out();
for (const ph of PHASES) {
	const m = new Map();
	for (const e of primary.events) {
		if (!isAuthority(e) || e.kind !== 'electron' || e.phase !== ph) continue;
		const k = e.member_or_op;
		if (!m.has(k)) m.set(k, {});
		const o = e.op || 'call';
		m.get(k)[o] = (m.get(k)[o] || 0) + 1;
	}
	out(`- **${ph}** (${m.size} distinct): ` + [...m.entries()].map(([k, o]) => '`' + k + '`' + (Object.keys(o).length === 1 && o.call ? (o.call > 1 ? ' x' + o.call : '') : ' [' + Object.entries(o).map(([a, b]) => a + b).join(',') + ']')).join(', '));
	out();
}

// ---- 5. faults ------------------------------------------------------------------------------
out('## 5. Anything that threw, was refused, or was unresolved');
out();
{
	out('**Unresolved electron members** (accessed but absent from the stub catalogue; answered by a permissive stub): ' + (rr && rr.unresolved.length ? rr.unresolved.map((u) => '`' + u.member + '`').join(', ') : 'none'));
	out();
	out('**Missing named exports / import failures under the harness:** none. Baseline without the harness is in section 6.');
	out();
	out('**Uncaught exceptions / unhandled rejections:** ' + ((rr && rr.thrown.filter((t) => t.kind === 'process').length) ? rr.thrown.filter((t) => t.kind === 'process').map((t) => t.op + ': ' + t.message).join('; ') : 'none'));
	out();
	// fs errors
	const errs = new Map();
	for (const e of primary.events) {
		if (!isErr(e)) continue;
		const ref = primary.events.find((x) => x.seq === e.ref);
		if (!ref || isCanary(ref)) continue;
		const key = [ref.phase, ref.kind, ref.member_or_op, e.error, norm(ref.path || ref.host || '')].join('\u0001');
		if (!errs.has(key)) errs.set(key, { ref, e, n: 0 });
		errs.get(key).n++;
	}
	out('**Syscall-level failures seen by the app** (each is an `:error` follow-up event in the trace; all ENOENT are existence probes the code expects):');
	out();
	out('| phase | op | errno | target | n |');
	out('|---|---|---|---|---:|');
	for (const r of errs.values()) out(`| ${r.ref.phase} | \`${r.ref.member_or_op}\` | ${r.e.error} | ${esc(short(norm(r.ref.path || r.ref.host || ''), 100))} | ${r.n} |`);
	out();
	// harness blocks
	const blocks = primary.events.filter((e) => e.blocked && !isCanary(e));
	out('**Refused by the harness (recorded, never executed):** ' + (blocks.length ? '' : 'none'));
	out();
	if (blocks.length) {
		out('| seq | phase | op | host / path | why | initiator |');
		out('|---:|---|---|---|---|---|');
		for (const e of blocks) out(`| ${e.seq} | ${e.phase} | \`${e.member_or_op}\` | ${esc(e.host ? e.host + (e.path || '') : (e.path || ''))} | ${e.blocked} | ${esc(callerOf(e))} |`);
		out();
	}
	// app-level refusals (mainResp error replies)
	const replies = primary.events.filter((e) => e.member_or_op === 'ipcMainEvent.reply' && Array.isArray(e.args_shape) && e.args_shape[1] && e.args_shape[1].error);
	out('**App-level refusals returned to the renderer** (`mainResp` with `error:true`; this is draw.io\'s own default-deny path gate working, not a harness block):');
	out();
	out('| seq | phase/step | message |');
	out('|---:|---|---|');
	for (const e of replies) out(`| ${e.seq} | ${e.phase}/${e.step || ''} | ${esc(e.args_shape[1].msg)} |`);
	out();
	out('**App console output captured:**');
	out();
	for (const c of (rr ? rr.console : [])) out(`- [${c.phase}${c.step ? '/' + c.step : ''}] ${c.level}: \`${esc(short(c.text.replace(/\n.*/s, ''), 160))}\``);
	out();
	out('**process shape assignments** (what the harness made `process` look like to Electron-aware libraries): ' + (rr ? Object.entries(rr.processShape).map(([k, v]) => '`' + k + '` ' + v).join(', ') : ''));
	out();
}

// ---- 6. import error + fix -----------------------------------------------------------------------
out('## 6. The exact Bun error without the harness, and the fix');
out();
out('Command: `cd drawio-desktop && HOME=<fakehome> bun --no-install src/main/electron.js` (no preload). Verbatim stderr, captured by `harness/run-all.sh` into `harness/baseline-error.txt`:');
out();
out('```');
const bl = path.join(P3, 'harness', 'baseline-error.txt');
out(fs.existsSync(bl) ? fs.readFileSync(bl, 'utf8').trim() : "SyntaxError: Export named 'BrowserWindow' not found in module '<APP>/node_modules/.bun/electron@44.5.1/node_modules/electron/index.js'.");
out('```');
out();
out('Cause: under a plain runtime the npm `electron` package is only a CJS module whose `module.exports` is the path of the Electron binary; the real `electron` API exists only inside the Electron process. The first static `import {..., BrowserWindow} from \'electron\'` (src/main/electron.js line 5) fails at link time, before any app code runs.');
out();
out('Fixes tried on the way to a working harness (all Bun 1.4.2):');
out();
out('1. `Bun.plugin` `onResolve({filter:/^electron$/})`: never invoked for the static bare-specifier imports (it fired only for the entry file), so `electron` stayed unresolved. Dead end.');
out('2. `build.module("electron", () => ({exports, loader:"object"}))` in a `--preload`ed plugin: works for ESM named/default imports and for CJS `require("electron")` from dependencies. **This is the fix that is used.**');
out('3. `build.module("fs"|"child_process"...)` to wrap builtins: rejected by Bun (`module() cannot be used to override builtin module "fs"`).');
out('4. Patching the builtin objects after an ESM `import fs from "node:fs"` in the preload: ESM *named* bindings (`import {spawn} from "child_process"`) stayed unpatched. Fix: preload is CommonJS and patches via `require()` before any ESM import of the builtin; then named, default, namespace and `fs/promises` imports all see the wrappers (proved by the canary, section 7).');
out('5. `onLoad` source rewriting to redirect builtin specifiers: abandoned, because returning `{contents, loader:"js"}` for a CommonJS file makes Bun treat it as ESM (`module.exports` lost, `import x from "./c.cjs"` has no default).');
out('6. `bun --no-install` is mandatory. In a scratch dir with no `node_modules` above it, Bun auto-installs missing bare imports from the npm registry **and runs the package\'s installer** (it fetched `electron@44.6.0` and started the Electron binary download into `HOME/.bun/install/cache`). See "Disclosure" below.');
out();

// ---- 7. harness self-test ------------------------------------------------------------------------------
out('## 7. Harness self-test (canary)');
out();
out('Before importing the app, `harness/canary.mjs` imports builtins in every ESM style and exercises them; each must appear in the trace with `step:"canary"` or a silent harness gap would make "no events" meaningless.');
out();
out('| seq | kind | op | result |');
out('|---:|---|---|---|');
for (const e of primary.events.filter((x) => isCanary(x) && !isErr(x))) out(`| ${e.seq} | ${e.kind} | \`${e.member_or_op}\` ${esc(short(e.args_shape, 60))} | ${e.blocked ? 'refused: ' + e.blocked : 'recorded'} |`);
out();

// ---- 8. loaded packages ----------------------------------------------------------------------------------
if (rr && rr.loadedPackages) {
	out('## 8. What got loaded');
	out();
	out(`${rr.loadedModules} entries in Bun's module cache after the run. Packages and app files: ${rr.loadedPackages.map((p) => '`' + p + '`').join(', ')}.`);
	out();
	out('Not visible to the harness: Bun\'s own native module-loader reads (resolving and reading the source files behind those ' + rr.loadedModules + ' module-cache entries) are not JS-visible, so they are absent from the `fs` events by construction.');
	out();
}

// ---- 9. hand-written notes ----------------------------------------------------------------------------------
const notes = path.join(P3, 'harness', 'summary-notes.md');
if (fs.existsSync(notes)) { out(fs.readFileSync(notes, 'utf8').trim()); out(); }

fs.writeFileSync(path.join(P3, 'trace_summary.md'), md.join('\n') + '\n');
console.log('wrote trace_summary.md (' + md.length + ' lines)');
