"""Apply batch-2 (doctrine audit) results to GitHub. Idempotent via apply_state.json.
Usage: python3 apply_batch2.py <result.json> [--dry-run] [--close]"""
import json, subprocess, sys, time, os, re, collections
res=json.load(open(sys.argv[1])); dry='--dry-run' in sys.argv; do_close='--close' in sys.argv
plan=json.load(open('publish_plan.json')); nums=json.load(open('publish_state.json')); swarm=json.load(open('swarm.json'))
REPO='gyldlab/keld'; SP='apply_state.json'; st=json.load(open(SP)) if os.path.exists(SP) else {}
by={i['key']:i for i in plan['issues']}
PROV="> Generated by an AI agent (Claude Code, Fable 5.1) on behalf of @0monish, 2026-10-06, under the map's execution doctrine. Statements are labelled FACT / INFERENCE / UNKNOWN by their author; nothing here authorizes implementation."
def scrub(t):
    t=re.sub(r'/private/tmp/claude-501/[^\s)\]`"\']*scratchpad','<scratchpad>',t); t=re.sub(r'<prompt-tracker clone>','<prompt-tracker clone>',t)
    t=re.sub(r'<keld repo>','<keld repo>',t); t=re.sub(r'<home>)\]`"\']*','<home>',t); return t
def ref(k): return f"#{nums[k]['number']}" if k in nums else k
def linkkeys(t): return re.sub(r'\b((?:F0\d|X0\d)-(?:EPIC|[TADE]\d+)|PANEL-[DP]\d+)\b', lambda m: f"{m.group(1)} ({ref(m.group(1))})" if m.group(1) in nums else m.group(1), t)
def gh(args, inp=None):
    for a in range(6):
        p=subprocess.run(['gh','api']+args,input=inp,capture_output=True,text=True)
        if p.returncode==0: return p.stdout
        e=p.stderr+p.stdout
        if any(x in e.lower() for x in ('rate limit','abuse','secondary')): time.sleep(min(90,10*(a+1))); continue
        raise RuntimeError(e[:300])
    raise RuntimeError('retries exhausted')
def once(tag, fn):
    if st.get(tag) is True: return
    if dry: print('[dry]',tag); return
    try: fn(); st[tag]=True
    except RuntimeError as e: st[tag]='failed: '+str(e)[:200]; print('FAIL',tag,str(e)[:200])
    json.dump(st,open(SP,'w'),indent=1)
def comment(key, body, tag):
    body=scrub(body)[:64000]
    once(f'comment:{key}:{tag}', lambda: (gh(['-X','POST',f"repos/{REPO}/issues/{nums[key]['number']}/comments",'--input','-'],inp=json.dumps({'body':body})), time.sleep(0.7)))
def label(key, lab): once(f'label:{key}:{lab}', lambda: (gh(['-X','POST',f"repos/{REPO}/issues/{nums[key]['number']}/labels",'--input','-'],inp=json.dumps({'labels':[lab]})), time.sleep(0.4)))
def L(xs): xs=[x for x in (xs or []) if x]; return '\n'.join(f'- {x}' for x in xs) if xs else '- none'
MS={'first-proof':'milestone:first-proof','next':'milestone:next','parked':'milestone:parked'}
def ms(v):
    v=(v or '').lower()
    for k,l in MS.items():
        if k in v: return l
# ---- 1. refuter verdicts per unit
vu=collections.defaultdict(list)
for v in res.get('verdicts') or []: vu[v['unit']].append(v)
verd_by_dec=collections.defaultdict(dict)   # decision id -> lens -> verdict
for u in swarm['units']:
    for vs in u.get('verdicts') or []:
        lens='invariants' if 'invariant' in (vs.get('lens','').lower()) else 'semantics'
        for x in vs.get('verdicts',[]): verd_by_dec[x['decision_id']][lens]=x.get('verdict','')
for unit,vs in vu.items():
    lines=[PROV,'',f'## Independent refuter verdicts — unit {unit}','',"Each decision of this unit's research was attacked by fresh-context refuters whose default position was that the decision is wrong.",'']
    for v in vs:
        lines.append(f"### Lens: {v['lens']}"); lines.append('')
        for x in v['verdict'].get('verdicts',[]):
            verd_by_dec[x['decision_id']][v['lens']]=x.get('verdict','')
            lines.append(f"- **{x['decision_id']}** → **{x.get('verdict','?')}** — {x.get('reason','')}" + (f"\n  - Correction: {x['correction']}" if x.get('correction') else '') + (f"\n  - Evidence: {x['evidence']}" if x.get('evidence') else ''))
        ef=v['verdict'].get('extra_findings') or []
        if ef: lines.append(''); lines.append('Extra findings:'); lines+= [f"- [{e.get('severity','')}] {e.get('finding','')}" + (f" — {e.get('evidence','')}" if e.get('evidence') else '') for e in ef]
        lines.append('')
    target=f'{unit}-EPIC' if f'{unit}-EPIC' in nums else 'MAP'
    comment(target, linkkeys('\n'.join(lines)), f'verdicts-{unit}')
# ---- 2. decision packets
closable=[]
for g in res.get('packets') or []:
    for p in g.get('packets',[]):
        k=p['key']
        if k not in nums: print('packet for unknown key',k); continue
        alts='\n'.join(f"| {a.get('option','')} | {a.get('cost','')} | {a.get('new_invariant','') or '—'} | {a.get('invariant_at_risk','') or '—'} |".replace('\n',' ') for a in p.get('alternatives',[]))
        body=f"""{PROV}

## Decision packet

**Decision:** {p['decision']}

**Classification:** `{p.get('classification','')}` · **Milestone (YAGNI test against the first proof):** `{p.get('milestone','')}` · **Reversible:** {p.get('reversible','') or '—'} · **Owner:** {p.get('owner','') or '—'}

### Facts
{L(p.get('facts'))}

### Inferences
{L(p.get('inferences'))}

### Unknowns
{L(p.get('unknowns'))}

### Alternatives

| Option | Cost | New invariant created | Existing invariant at risk |
|---|---|---|---|
{alts or '| — | — | — | — |'}

### Recommendation
{p.get('recommendation','')}

**Falsifier:** {p.get('falsifier','')}

**Missing evidence:** {p.get('missing_evidence','') or 'none'}

**Next action:** {p.get('next_action','')}
"""
        if (p.get('prompt_tracker_node') or '').strip():
            body+=f"\n<details><summary>Copy-ready Prompt Tracker node draft (to be filed in the tracker's existing taxonomy by its single writer)</summary>\n\n```text\n{p['prompt_tracker_node'].strip()}\n```\n\n</details>\n"
        comment(k, linkkeys(body), 'packet')
        m=ms(p.get('milestone'))
        if m: label(k,m)
        v=verd_by_dec.get(k,{})
        if 'decided' in (p.get('classification','').lower()) and v.get('invariants','').lower().startswith('surviv') and v.get('semantics','').lower().startswith('surviv'): closable.append((k,p))
print('closable (decided + both lenses survive):',[k for k,_ in closable])
if do_close:
    for k,p in closable:
        comment(k, f"{PROV}\n\n## Resolution\n\n{p['recommendation']}\n\nResolved under the user's delegation: the decision packet classifies it as decided on current evidence and both independent refuter lenses (Keld invariants; Electron semantics) returned *survives*. Reopen by comment with contrary primary evidence.", 'resolution')
        once(f'closed:{k}', lambda k=k: gh(['-X','PATCH',f"repos/{REPO}/issues/{nums[k]['number']}",'--input','-'],inp=json.dumps({'state':'closed','state_reason':'completed'})))
# ---- 3. critic
c=res.get('critic') or {}
for y in c.get('yagni') or []:
    if y['key'] in nums and ms(y.get('milestone')): label(y['key'], ms(y['milestone']))
per=collections.defaultdict(list)
for kind,items,fmt in (('Edge',c.get('edge_problems'),lambda x:f"{x.get('problem','')} → Fix: {x.get('fix','')}"),('Invariant',c.get('invariant_violations'),lambda x:f"{x.get('violation','')} → Fix: {x.get('fix','')}"),('Quality',c.get('quality_problems'),lambda x:f"{x.get('problem','')} → Fix: {x.get('fix','')}"),('Ambiguity (stated as fact)',c.get('ambiguity_laundering'),lambda x:f"Claim: “{x.get('claim','')}” — {x.get('problem','')} → Fix: {x.get('fix','')}")):
    for x in items or []:
        if x.get('key') in nums: per[x['key']].append(f"**{kind}:** {fmt(x)}")
for kind,items,fmt in (('Duplicate / one-owner',c.get('duplicates'),lambda x:f"{x.get('problem','')} → Fix: {x.get('fix','')}"),('Hidden coupling',c.get('hidden_coupling'),lambda x:f"{x.get('coupling','')} → Fix: {x.get('fix','')}")):
    for x in items or []:
        for k in x.get('keys') or []:
            if k in nums: per[k].append(f"**{kind}** (with {', '.join(kk for kk in x.get('keys',[]) if kk!=k)}): {fmt(x)}")
yag={y['key']:y for y in c.get('yagni') or []}
for k,fs in per.items():
    y=yag.get(k); extra=f"\n\n**YAGNI classification:** `{y['milestone']}` — {y['reason']}" if y else ''
    comment(k, linkkeys(f"{PROV}\n\n## Doctrine audit findings for this issue\n\n"+L(fs)+extra+"\n\nDisposition: each finding stays open on this issue until its fix is applied to the body or refuted with evidence."), 'audit')
for k,y in yag.items():
    if k in nums and k not in per: comment(k, linkkeys(f"{PROV}\n\n**YAGNI classification (doctrine audit):** `{y['milestone']}` — {y['reason']}"), 'yagni')
fr='\n'.join(f"{n+1}. {ref(x['key'])} `{x['key']}` — {x.get('why_now','')}" + (f" *(consumes: {x['consumes']})*" if x.get('consumes') else '') for n,x in enumerate(c.get('first_proof_frontier') or []))
cov=L([f"`{g.get('entity','')}` — {g.get('problem','')} (suggested: {g.get('suggested_unit','')})" for g in c.get('coverage_gaps') or []])
hc=L([f"{', '.join(x.get('keys') or [])}: {x.get('coupling','')} → {x.get('fix','')}" for x in c.get('hidden_coupling') or []])
mc=collections.Counter(ms(y.get('milestone')) for y in c.get('yagni') or [])
if c: comment('MAP', linkkeys(f"""{PROV}

## Doctrine audit of the published plan

{c.get('summary','')}

### First-proof frontier (ordered; drawio-desktop on macOS, explicit legacy profile)

{fr or '- none returned'}

### YAGNI classification of the {sum(mc.values())} classified tickets

{L([f'`{k}`: {v}' for k,v in mc.items() if k])}

### Hidden coupling made explicit

{hc}

### Coverage gaps (Electron entities not yet covered by a ticket, epic scope, never list or out-of-scope)

{cov}

Counts: {len(c.get('duplicates') or [])} duplicate/one-owner findings, {len(c.get('edge_problems') or [])} edge problems, {len(c.get('invariant_violations') or [])} invariant findings, {len(c.get('quality_problems') or [])} quality findings, {len(c.get('ambiguity_laundering') or [])} ambiguity findings — each posted on its owning issue.
"""), 'audit-summary')
bad={k:v for k,v in st.items() if v is not True}; print('applied ops:',len(st),'| failed:',len(bad), list(bad.items())[:5])
