# Hand-drafted ticket plan (part 1): helpers + F01, F02, F03
import json
DRAFTS={}
def brief(kind, current, desired, interfaces, oos):
    return (f"**Category:** {kind}\n\n**Current behavior:** {current}\n\n**Desired behavior:** {desired}\n\n"
            f"**Key interfaces:** {interfaces}\n\n**Acceptance criteria:** the checklist above, each as a test with its negative control.\n\n**Out of scope:** {oos}")
def T(key,title,kind,tier,mat,what,ac,neg,blocked=(),ext=(),owner='none — maintainer to bridge',gates=('none',),plat='macOS first; Windows/Linux lanes or explicit documented gap',members=(),size='M',ready='needs-spec',current='',interfaces='',oos='',notes=''):
    return {'key':key,'title':title,'kind':kind,'tier':tier,'maturity_target':mat,'what_to_build':what,'acceptance_criteria':list(ac),'negative_controls':list(neg),'blocked_by_keys':list(blocked),'blocked_by_external':list(ext),'linear_owner':owner,'review_gates':list(gates),'platforms':plat,'electron_members_covered':list(members),'size':size,'ready_state':ready,'agent_brief':brief(kind,current,what if not interfaces else what,interfaces,oos),'out_of_scope':oos,'notes':notes}
def D(key,title,typ,question,status='open',resolution='',evidence=(),blocked=()):
    return {'key':key,'title':title,'type':typ,'question':question,'status':status,'resolution':resolution,'resolution_evidence':list(evidence),'blocked_by_keys':list(blocked)}
def unit(key,epic_title,tier,epic_body,tickets,decisions,never,oos,fog,blocked=()):
    DRAFTS[key]={'unit':key,'epic':{'key':f'{key}-EPIC','title':epic_title,'body':epic_body,'tier':tier,'blocked_by_keys':list(blocked)},'tickets':tickets,'decision_tickets':decisions,'out_of_scope':oos,'not_yet_specified':fog,'never_list':never}

# ---------------- F01 app lifecycle ----------------
unit('F01','compat(app): Electron app lifecycle, single-instance, paths and process shim over host-owned lifecycle','Tier 1',
"""## Scope
Electron `app` module (115 members: 75 methods, 30 events, 10 properties), `CommandLine` (5), `Dock` (11, macOS), `process` shim (29). Live today: `app.whenReady/isReady/quit/on/off/removeListener`, `ready` and `window-all-closed` events, `process.type='browser'`, `process.versions.electron='0.0.1'` (KEL-72). Everything else is TARGET.

## Corpus demand (resolved call sites, 2026-10-06)
whenReady/ready, window-all-closed, quit, exit, getPath (Zettlr ~40 sites, draw.io 3), getVersion, requestSingleInstanceLock + second-instance (both apps), open-file (Zettlr), before-quit/will-quit, activate, relaunch (Zettlr), isPackaged, setAppUserModelId, disableHardwareAcceleration, process.argv/defaultApp parsing (draw.io).

## Maturity ladder (exit criteria)
- L0: every `app` member exists with a typed `KELD-COMPAT` error for unsupported calls (never a silent no-op).
- L1: electron-quick-start and draw.io boot through `whenReady`, `activate`, `window-all-closed`, `quit` on macOS.
- L2: ordering sequences `before-quit → per-window close → will-quit → quit` (and the `quitAndInstall` inversion) pass conformance entries citing the pinned v44.4.5 `app.md` sentences, with negative controls; `second-instance` delivered exactly once with typed argv/cwd.
- L3: draw.io and Zettlr primary workflows exercise the family under `keld dev` (KEL-74 records, authority profile printed).

## Linear owners consumed
KEL-72 (lifecycle facade), KEL-142 (@keld/api lifecycle/channel), KEL-139/KEL-143 (Ready and generation recovery semantics), KEL-75 (role spawn facts), KEL-78 (strict child environment), KEL-19/KEL-15 (config/bundle emission), KEL-96 (keld dev exit codes).

## Design facts fixed by research (two refuters)
- Host `Ready` is emitted today on the first host-created window's navigation; Electron's `ready` fires before any window exists. Ready must be re-based to "host initialized, window module available" while keeping the wire enum unchanged (KEL-237 cells stay valid) and pairing the re-base with KEL-143 recovery semantics.
- Quit is one-shot and uncancelable today; Electron's cancelable `before-quit`/`will-quit` and renderer `beforeunload` need a two-phase, host-owned protocol. `app.exit(code)` cannot be `process.exit` (the supervisor would recover the role); it is a host Call.
- The strict Bun child receives only `KELD_APP_LINK` and log sinks, so single-instance, second-instance argv/cwd/additionalData, open-file/open-url, path roots and OS registrations are host-owned and delivered as typed events or boot facts.
- Protocol-client and login-item registration are build-time declarations materialised by packaging; the facade reports false with a diagnostic until an emitter exists.
- `app.commandLine.*` is a facade-local self-consistent store with a one-time dev warning (arbitrary Chromium flags are documented-never).

## Platform lanes
macOS first (Dock, open-file/open-url, activate, Handoff APIs are macOS-tagged: 44 members); Windows (jump lists, AppUserModelId, toast activator: 20 members); Linux (badge, desktop name: 4 members). `before-quit/will-quit/quit` are not emitted on Windows shutdown — documented ▲.
""",
[
 T('F01-T1','conformance(app): pinned v44.4.5 lifecycle ordering entries before any new app facade code','conformance','Tier 1','L2',
   'Land Keld-owned conformance entries (fixture + test citing the exact pinned `app.md` sentence) for: `ready` fires once before any window; `before-quit → close each window → will-quit → quit` ordering; `preventDefault` at `before-quit` or any window `close` cancels quit; `will-finish-launching` equals `ready` on Windows/Linux; `window-all-closed` default quit; `activate(hasVisibleWindows)` on macOS. Entries may fail (red) until the implementing tickets land; they must not be skipped or retried.',
   ['Each entry cites the pinned v44.4.5 doc sentence (blob at the v44.4.5 tag) and names its observable sequence','Every entry has a negative control that fails when the ordering is deleted or reversed','Entries run in the existing three-OS test matrix without sleeps; timing is never compared','The KEL-237 lifecycle corpus manifest schema is reused; no second corpus format is introduced'],
   ['Reversing before-quit and will-quit in the fixture fails the ordering entry','Removing the preventDefault branch fails the cancellation entry'],
   ext=['KEL-237 corpus manifest (reuse)','KEL-72 fixtures (extend, do not fork)'],owner='KEL-237 / KEL-72',gates=['none'],members=['ready','before-quit','will-quit','quit','window-all-closed','activate','will-finish-launching','whenReady','isReady'],size='M',ready='ready-for-agent',
   current='Only `ready`, `window-all-closed` and `quit` are covered by conformance cells.',interfaces='KEL-237 corpus manifest cells; the `@keld/electron` fixture runner; pinned Electron `app.md`.',oos='Implementing the ordering; renderer `beforeunload`; Windows shutdown semantics beyond documenting the ▲.'),
 T('F01-T2','feat(app): re-base host Ready to "host initialized, zero app windows" and keep KEL-237 cells valid','feature','Tier 1','L2',
   'Change the host emission point of the lifecycle `Ready` event so it fires once the host is initialised and the window module is available, before any app window exists, matching Electron `ready`; keep the wire enum unchanged. Window creation moves to the facade (`new BrowserWindow`) once F02 lands; until then the host-created primary window is adopted by the facade. Pair the semantics with KEL-143 recovery (a successor generation receives Ready again with the same meaning).',
   ['`app.whenReady()` resolves before any window exists and exactly once per generation','The KEL-237 `app.when-ready.host-ready-gate` cell still passes (no wire change)','KEL-143 successor generation observes Ready again and can re-adopt the surviving window','A fixture that registers `ready` after the event fires still receives it (Electron semantics)'],
   ['Emitting Ready on window navigation again fails the "before any window" entry','Dropping the successor Ready fails the KEL-143 recovery entry'],
   blocked=['F01-T1'],ext=['KEL-143 task-level artifact (recovery contract)','KEL-139 AC for Ready'],owner='KEL-139 / KEL-143',gates=['public API'],members=['ready','whenReady','isReady'],size='M',ready='needs-spec',
   current='Ready is signalled on the first host-created window navigation.',interfaces='Lifecycle session Ready emission; `@keld/api` app lifecycle; the host window registry (TARGET).',oos='BrowserWindow constructor (F02); two-phase quit (F01-T3).'),
 T('F01-T3','feat(app): two-phase host-owned quit with before-quit/will-quit cancellation and app.exit as a host Call','feature','Tier 1','L2',
   'Make quit two-phase: the facade emits `before-quit` locally for facade-initiated quit, then asks the host to close all windows through the cancelable per-window close protocol (F02), then emits `will-quit`, then issues the existing Quit Call. Host-initiated quit (Cmd+Q, dock, logoff) arrives as a host event the facade handles the same way; any `preventDefault` or a window-close veto cancels and the host stays alive. `app.exit(code)` becomes a host Call that terminates the generation without supervisor recovery; the `keld dev` exit-code contract is a named prerequisite.',
   ['Sequence `before-quit → close(window n) … → will-quit → quit` matches the conformance entry','`preventDefault()` in `before-quit` keeps every window open and the app alive','`app.exit(7)` exits the host session with status 7 under `keld dev` (CLI contract) and never triggers a restart','`quitAndInstall` ordering is split by facade × platform as documented (see F09)'],
   ['Removing the cancellation path makes the preventDefault entry fail','Implementing app.exit as process.exit triggers supervisor recovery and fails the exit entry'],
   blocked=['F01-T1','F02-T3'],ext=['KEL-96/KEL-19 keld dev exit-code propagation','KEL-139 AC6 single quit owner'],owner='KEL-139 / KEL-96',gates=['wire protocol','public API'],members=['quit','exit','before-quit','will-quit','relaunch'],size='L',ready='needs-spec',
   current='Quit is a one-shot correlated Call with no veto; app.exit is absent.',interfaces='Lifecycle channel Quit/Exit requests; host quit sequencing (AppKit applicationShouldTerminate delayed reply); F02 close protocol.',oos='Window close protocol itself (F02-T3); updater-driven quit (F09).'),
 T('F01-T4','feat(app): host-minted boot facts for synchronous pre-ready getters (getPath, getVersion, getName, isPackaged, process.resourcesPath, argv)','feature','Tier 1','L1',
   'Deliver host-minted boot facts to the Bun role at spawn (beside `KELD_APP_LINK`, owned by the role spawn contract) so `app.getPath(name)`, `getAppPath`, `getVersion/getName/name`, `isPackaged`, `process.resourcesPath/defaultApp/argv` are synchronous at module evaluation (draw.io constructs electron-store at top level). The facade never reads HOME/APPDATA/XDG itself. Where `userData` lives under the strict profile is decided by F01-A4 (open).',
   ['`app.getPath("userData")` returns synchronously at import before `whenReady`','`isPackaged` is false under `keld dev` and true under an installed root','`process.argv` matches Electron: first element is the executable, app arguments follow','A role spawned without boot facts fails closed with a typed `KELD-COMPAT` error naming the missing fact'],
   ['Removing the boot-fact delivery makes the import-time getPath entry throw','Reading HOME inside the facade fails the "no environment reads" negative test under the Linux explicit-env strict launch'],
   blocked=['F01-A4'],ext=['KEL-75 role spawn contract (boot facts beside KELD_APP_LINK)','KEL-15 config schema for name/version'],owner='KEL-75 / KEL-15',gates=['public API'],members=['getPath','setPath','getAppPath','getVersion','getName','name','isPackaged','getLocale','getSystemLocale','process.resourcesPath','process.defaultApp','process.argv'],size='M',ready='needs-spec',
   current='`@keld/electron` exposes nothing synchronous at import beyond process.type/versions.',interfaces='Role spawn bootstrap payload; `@keld/electron` app getters; `keld.config.ts` identity fields.',oos='Granting filesystem authority over those paths (F01-A4 / KEL-78).'),
 T('F01-T5','feat(app): host-owned single-instance admission with exactly-once typed second-instance, open-file and open-url delivery','feature','Tier 1','L2',
   'The host owns the OS single-instance primitive (declared in `keld.config.ts`), pre-acquires it so the primary identity exists before Bun, and preserves Electron call-time semantics: `requestSingleInstanceLock()` returns the host verdict (the losing instance still runs its early CLI paths), `second-instance` delivers `(argv, workingDirectory, additionalData)` as opaque untrusted data exactly once after `ready`, and macOS `open-file`/`open-url` may precede `ready` and are queued per Electron rules. OS-delivered file intents become host-scoped one-shot read intents, never ambient grants.',
   ['Second launch delivers one `second-instance` event with the exact argv/cwd the OS supplied and the first instance is focused','`open-file` fired before `ready` is delivered after the listener registers (Electron queueing)','Calling `requestSingleInstanceLock()` without a config declaration yields a typed `KELD-COMPAT` diagnostic','Replayed or duplicated handoff payloads are rejected (bounded size, exactly-once)'],
   ['Delivering second-instance twice fails the exactly-once entry','Forwarding argv straight to a privileged handler fails the untrusted-input negative test'],
   blocked=['F01-T1','F01-T4'],ext=['KEL-75 role spawn','KEL-78 strict environment','arch 05 §3 deeplink row'],owner='KEL-75 / KEL-78',gates=['permission model','wire protocol'],members=['requestSingleInstanceLock','hasSingleInstanceLock','releaseSingleInstanceLock','second-instance','open-file','open-url','setAsDefaultProtocolClient','isDefaultProtocolClient'],size='L',ready='needs-spec',
   current='No single-instance or deep-link concept exists; keld-native lists `deeplink` as a name only.',interfaces='Host deeplink admission point; lifecycle-adjacent typed events; `keld.config.ts` singleInstance/protocols declarations.',oos='Build-time protocol/login-item registration emitters (F01-T6).'),
 T('F01-T6','task(app): facade-local shims with honest diagnostics (commandLine, enableSandbox, protocol-client and login-item registration before the packaging emitter exists)','task','Tier 1','L0',
   '`app.commandLine.*` keeps a private switch map (self-consistent append/has/get/remove) and emits one dev-only `KELD-COMPAT` warning per switch; `enableSandbox()` is a no-op that still throws after ready like Electron; `setAsDefaultProtocolClient`/`setLoginItemSettings` return false with a diagnostic naming the missing packaging emitter until keld-pack materialises declarations; `process.noAsar` is documented-never.',
   ['`appendSwitch("x","1")` then `getSwitchValue("x")` returns "1" and the engine command line is untouched','`enableSandbox()` after ready throws the Electron error text','`setAsDefaultProtocolClient("drawio")` returns false and the diagnostic names the emitter ticket','Scoreboard rows record ▲/✘ for every member in this ticket'],
   ['Making setAsDefaultProtocolClient return true without an emitter fails the honesty entry'],
   blocked=['F01-T1'],owner='KEL-72',gates=['none'],members=['commandLine.appendSwitch','commandLine.appendArgument','commandLine.hasSwitch','commandLine.getSwitchValue','commandLine.removeSwitch','enableSandbox','setAsDefaultProtocolClient','removeAsDefaultProtocolClient','setLoginItemSettings','getLoginItemSettings','process.noAsar'],size='S',ready='ready-for-agent',
   current='None of these members exist on the facade.',interfaces='`@keld/electron` app module; scoreboard rows.',oos='Real OS registration (needs the packaging emitter: KEL-19).'),
],
[
 D('F01-A4','Where does `userData` live under the strict profile: guard grant root or KEL-78 role-private container?','grilling',
   'Electron apps (electron-store, electron-log) write under `app.getPath("userData")` with raw `node:fs`. Making `userData` a generated `app.fs.*` grant root contradicts KEL-78 (a guard grant is not OS containment and a JS shim cannot mediate native code). Choose one owner: (a) place `userData`/`logs` inside the KEL-78 reviewed role-private container so `node:fs` works by OS containment with no guard grant, or (b) a `node:fs`-over-FsBroker facade for strict roles. Which, and what does `keld migrate` print for apps that need the other?',
   blocked=[]),
 D('F01-A5','Which owner emits bundle declarations (Info.plist CFBundleURLTypes, .desktop, MSIX) for protocol-client and login-item registration?','task',
   'Protocol-client and login-item registration are build-time declarations. keld-pack is a name-only enum today and KEL-19 may or may not include bundle emission. Confirm the owner and the `keld.config.ts` fields (KEL-15) before F01-T6 can be promoted beyond "false with diagnostic". This is a permission-model + KEL-15 schema gate.'),
],
['process.noAsar / original-fs (no ASAR in Keld)','arbitrary Chromium/V8 flags through commandLine (facade-local store only)','app.setAsDefaultProtocolClient claiming success without a bundle declaration','process.exit-based app.exit (supervisor would recover the role)'],
['Handoff/continuity macOS APIs beyond documenting ✘ (zero corpus demand)','Windows shutdown-block APIs beyond the documented ▲'],
['Exact BootDescriptor field set (decided when F01-T4 lists pre-ready calls from the draw.io boot trace)','Pre-ready event queueing rules across second-instance vs open-file/open-url (Electron orders them differently)'])

# ---------------- F02 windowing ----------------
unit('F02','compat(window): BaseWindow/BrowserWindow over the host window registry — identity, cancelable close, ready-to-show, chrome options','Tier 1',
"""## Scope
32 entities / 606 raw members: `BaseWindow` (187) and `BrowserWindow` (204, 126 inherited), constructor option structures (52 + 2 fields), `WebPreferences` (46 fields), `View`/`WebContentsView`/`BrowserView`/`ImageView`, 11 TouchBar classes (macOS), JumpList/Thumbar structures (Windows). Live today: the host owns exactly one primary window per session, created after the authenticated HELLO before Bun code runs; close is uncancelable; no window id crosses kipc; no chrome options exist; the destination window registry is TARGET.

## Corpus demand
Constructor + `show:false` + `ready-to-show` + `backgroundColor` (Zettlr 14 sites, draw.io), cancelable `close` with async veto then explicit `destroy()` (both apps), `closed` bookkeeping, `isDestroyed`, `getAllWindows/getFocusedWindow/fromWebContents`, maximize/minimize/fullscreen state + events, macOS `hiddenInset` + `trafficLightPosition`, Windows/Linux `frame:false` + `titleBarOverlay` (Zettlr), parent/modal (Zettlr), `setWindowOpenHandler` with `overrideBrowserWindowOptions` (draw.io).

## Maturity ladder
- L0: `BrowserWindow` class exists; unsupported options throw typed errors (privilege-escalating `webPreferences` fail loudly; engine-only flags are ignored with a diagnostic).
- L1: electron-quick-start runs unmodified on macOS (`new BrowserWindow`, `loadFile`, `getAllWindows`, close → closed).
- L2: two-phase close, tombstone-before-`closed`, `show:false`/`ready-to-show`, state events pass conformance entries citing the pinned `browser-window.md`/`base-window.md` sentences; the window-state mirror is proven coherent under a 10k-event stream.
- L3: draw.io and Zettlr window workflows pass under `keld dev` with KEL-74 records.

## Linear owners consumed
KEL-139/KEL-142 (host-created primary window, bridge), KEL-143 (window survives Bun generation loss), KEL-75 (WindowGeneration minting, window-bound roles), KEL-135 (profiles), KEL-132 (GPU/media), KEL-98 (contract codegen is NOT general — a window channel needs its own contract owner), KEL-64 (double-rAF technique for paint oracle).

## Design facts fixed by research (two refuters)
- The host mints opaque `(WindowId, WindowGeneration)`; the facade keeps a synchronous mirror updated by ordered host events before any user listener runs. `getAllWindows()` ordering is Keld-stronger than Electron (documented ▲-stronger).
- The host already creates the primary window before Bun runs; the first `new BrowserWindow()` adopts it (explicitly recorded) until Ready is re-based (F01-T2).
- Two-phase close owned by the host: `CloseRequested{window, generation, seq}` → facade emits `close` synchronously → `CloseAllow`/veto reply. The host waits indefinitely while the owning Bun generation is alive (Electron's delegate returns NO and waits); it closes on its own only when the generation is revoked. No host auto-close on timeout.
- Tombstone flips before `closed`; later member access throws the exact `Object has been destroyed` text; `destroy()` skips `close` and guarantees `closed`.
- `WebPreferences` triage: privilege-escalating fields (nodeIntegration, contextIsolation:false, webSecurity:false, allowRunningInsecureContent, enableBlinkFeatures, experimentalFeatures) fail loudly ✘; engine-flag fields such as `disableBlinkFeatures` (draw.io sets it on every window) are ignored with a diagnostic ▲; `sandbox:false` is ▲ ignored-with-diagnostic and never selects a Keld profile.
- One `BaseWindow` implementation; `BrowserWindow = BaseWindow + exactly one host-created content view`; View tree, BrowserView and multi-view are Tier 3.

## Platform lanes
macOS first (titleBarStyle/trafficLightPosition via public NSWindow API; vibrancy is Tier 2 ▲), Windows (frame:false + titleBarOverlay needs the WebView2 non-client receipt — open research F02-A6), Linux (GTK CSD).
""",
[
 T('F02-T1','conformance(window): pinned v44.4.5 entries for close/closed/destroy/tombstone, ready-to-show, state events and identity','conformance','Tier 1','L2',
   'Land Keld-owned conformance entries (red until implemented): `close` before DOM `beforeunload`/`unload`, `preventDefault` cancels; `destroy()` skips `close` and guarantees `closed`; `isDestroyed()` is true inside a `closed` listener; property access after destruction throws `Object has been destroyed`; `ready-to-show` fires once when the hidden page has rendered; `maximize/unmaximize/minimize/restore/enter-full-screen/leave-full-screen/focus/blur/move/resize` sequences; `getAllWindows/getFocusedWindow/fromId` synchronous results.',
   ['Every entry cites the pinned doc sentence and names its ordered observable','Each entry has one negative control (reorder/delete) that fails','No entry compares wall-clock timing'],
   ['Emitting closed before the tombstone flips fails the isDestroyed-inside-closed entry'],
   ext=['KEL-237 corpus manifest (reuse)'],owner='KEL-237',gates=['none'],members=['close','closed','destroy','isDestroyed','ready-to-show','show','hide','focus','blur','maximize','unmaximize','minimize','restore','enter-full-screen','leave-full-screen','move','resize','getAllWindows','getFocusedWindow','fromId','fromWebContents'],size='M',ready='ready-for-agent',
   current='No BrowserWindow facade or window conformance entries exist.',interfaces='KEL-237 manifest cells; `@keld/electron` fixtures.',oos='Implementation.'),
 T('F02-T2','feat(window): host window registry with host-minted (WindowId, WindowGeneration) and a facade mirror for synchronous getters','feature','Tier 1','L1',
   'Make the host window registry live for app-created windows: mint `(WindowId, WindowGeneration)` per native window, emit ordered window-state events (created, bounds, focus, maximized, fullscreen, destroyed) over the app link, and give `@keld/api` a synchronous mirror consumed by `BrowserWindow.getAllWindows/getFocusedWindow/fromId/getBounds/isMaximized/...`. The first `new BrowserWindow()` adopts the host-created primary window until F01-T2 lands. Setters are write-through Calls confirmed by the host event.',
   ['`new BrowserWindow({show:false})` creates a native window on the host and returns an object whose `id` is host-minted','`getFocusedWindow()` reflects the last host-delivered focus event with zero kipc traffic per read','Mirror coherence: under a 10k-event/s synthetic stream no read observes an order inversion; zero steady-state allocation per read','A stale generation (after Bun recovery) cannot address a window from the previous generation (typed error)'],
   ['Minting ids in the facade fails the host-identity negative test','Delivering a state event after the user listener fails the ordering entry'],
   blocked=['F02-T1','PANEL-D19'],ext=['KEL-75 WindowGeneration','KEL-143 same-window recovery','window channel contract owner (open: KEL-98 is echo-only)'],owner='KEL-139 / KEL-143 / KEL-75',gates=['wire protocol','public API'],members=['constructor','id','getAllWindows','getFocusedWindow','fromId','getBounds','getSize','getPosition','setBounds','setSize','setPosition','isMaximized','isMinimized','isFullScreen','isFocused','isVisible','show','hide','focus','blur','maximize','unmaximize','minimize','restore','setFullScreen','setTitle','getTitle'],size='L',ready='needs-spec',
   current='One host-created primary window; no id crosses kipc; the registry is TARGET.',interfaces='keld-core window registry; a generated `window.*` channel contract (owner to be named); `@keld/api` window mirror; `@keld/electron` BrowserWindow/BaseWindow classes.',oos='Cancelable close (F02-T3); chrome options (F02-T5); multi-view (Tier 3).'),
 T('F02-T3','feat(window): two-phase cancelable close, destroy and tombstone-before-closed with host-side AppKit/Win32/GTK veto hooks','feature','Tier 1','L2',
   'Implement the close protocol: native close request → host emits `CloseRequested{window, generation, seq}` without closing (AppKit `windowShouldClose:` returns NO; Win32 `WM_CLOSE` deferred; GTK `delete-event` handled) → facade emits `close` synchronously → reply allow/veto → on allow the host runs page unload, destroys the webview before the window, emits destroyed → facade flips the tombstone, then emits `closed`. `destroy()` skips `close`. The host waits while the owning generation is alive; it closes on its own only when the generation is revoked, with a diagnostic.',
   ['draw.io close dance (preventDefault every close → renderer isModified → decision → destroy) completes without data loss and without timeouts','`isDestroyed()` is true inside the `closed` listener; later `getBounds()` throws `Object has been destroyed`','Close requested while Bun is parked keeps the window open; when the generation is revoked the host closes and `window-all-closed` policy applies','`close()` twice is idempotent; `destroy()` after a vetoed close still emits `closed` exactly once'],
   ['Host auto-closing on a timeout fails the data-loss negative test','Emitting closed before destruction completes fails the tombstone entry'],
   blocked=['F02-T2','PANEL-P2'],ext=['KEL-143 generation revocation','KEL-139 T1b no fabricated completion'],owner='KEL-139 / KEL-143',gates=['wire protocol'],members=['close','closed','destroy','isDestroyed','closable','setClosable','window-all-closed'],size='L',ready='needs-spec',
   current='Close is uncancelable: the engine close request becomes LastWindowClosed immediately.',interfaces='keld-wv per-backend close veto hooks; window registry close state machine; facade `close` event with preventDefault.',oos='Renderer `beforeunload` (0 corpus demand; documented ▲ until KEL-79 provides a primitive).'),
 T('F02-T4','feat(window): WebPreferences triage — privilege-escalating fields fail loudly, engine flags are ignored with a diagnostic, sandbox:false never selects a profile','feature','Tier 1','L1',
   'Classify all 46 `WebPreferences` fields: privilege-escalating (nodeIntegration*, contextIsolation:false, webSecurity:false, allowRunningInsecureContent, enableBlinkFeatures, experimentalFeatures, enableRemoteModule, offscreen) → typed `KELD-COMPAT` error at construction (window not created) unless the per-window `keld.compat.ts` quirk explicitly accepts the forfeit; engine-flag fields (`disableBlinkFeatures`, `spellcheck` toggles, `v8CacheOptions`, …) → ignored with one diagnostic ▲; policy fields (`preload`, `additionalArguments`, `partition`, `session`, `devTools`, `zoomFactor`, `backgroundThrottling`) → mapped or ▲ per F03/F05; `sandbox:false` → ▲ ignored-with-diagnostic (never a Keld profile selector).',
   ['draw.io windows (which set `disableBlinkFeatures`) are created; the diagnostic appears once','A window with `nodeIntegration:true` is not created and the error text names the fix and the migrate report row','`keld migrate` reports every weak-isolation field per call site in the security section','Scoreboard rows exist for all 46 fields'],
   ['Honoring nodeIntegration:true silently fails the never-list negative test','Refusing disableBlinkFeatures fails the draw.io activation entry'],
   blocked=['F02-T2'],ext=['KEL-78 (sandbox is not a profile key)','X04 security mapping'],owner='KEL-78',gates=['permission model'],members=['webPreferences (46 fields)','BrowserWindowConstructorOptions'],size='M',ready='ready-for-agent',
   current='No WebPreferences handling exists.',interfaces='`BrowserWindow` constructor option validation; `keld.compat.ts` per-window quirks; migrate security report.',oos='Preload injection itself (F07).'),
 T('F02-T5','feat(window): Tier-1 chrome options on macOS (titleBarStyle hidden/hiddenInset, trafficLightPosition, frame:false, transparent, alwaysOnTop, skipTaskbar, closable/resizable/minimizable/maximizable, fullscreenable)','feature','Tier 1','L2',
   'Map the chrome options the corpus uses onto public NSWindow API on macOS (fullSizeContentView + titlebarAppearsTransparent + titleVisibility hidden; traffic-light positioning), plus the boolean capability flags; vibrancy/visualEffectState stay Tier 2 ▲; Windows/Linux `titleBarOverlay` waits on F02-A6.',
   ['Zettlr primary window renders with hiddenInset and custom traffic-light position on macOS','`setTitleBarOverlay` at runtime on Windows/Linux is either implemented or a typed ▲ naming F02-A6','Each option has a scoreboard row (✔/▲/✘) with a conformance entry'],
   ['Removing the titlebar mapping fails the Zettlr chrome entry'],
   blocked=['F02-T2'],owner='KEL-139',gates=['none'],members=['titleBarStyle','trafficLightPosition','frame','transparent','alwaysOnTop','skipTaskbar','closable','resizable','minimizable','maximizable','fullscreenable','backgroundColor','vibrancy','visualEffectState','titleBarOverlay','setTitleBarOverlay'],size='M',ready='needs-spec',plat='macOS first; Windows/Linux after F02-A6',
   current='No chrome options exist in any backend.',interfaces='keld-wv window creation options; BrowserWindow constructor option mapping.',oos='TouchBar, JumpList, Thumbar (Tier 2, platform epics later).'),
],
[
 D('F02-A3','Can `show:false` + `ready-to-show` + `backgroundColor` be honoured on system webviews (hidden-paint oracle)?','prototype',
   'Electron fires `ready-to-show` when the renderer first renders while hidden. Keld must create the native window unmapped and derive ready-to-show from a host-owned isolated-world double-rAF reporter per engine (the KEL-64 technique, not its benchmark instrument). WebView2 stops rendering when the controller is invisible (receipt needed). Cheapest experiment: in the existing hello, create the window without ordering it front on each OS and observe whether the first paint beacon fires while hidden; record per-engine ✔/▲.'),
 D('F02-A6','Which Windows/Linux chrome options (frame:false, titleBarStyle hidden, titleBarOverlay, setTitleBarOverlay) are Tier 1 and how are they implemented?','research',
   'Zettlr relies on `titleBarOverlay{color,symbolColor,height}` on Windows and Linux and switches it at runtime. Settle with receipts: WebView2 `ICoreWebView2Settings9.IsNonClientRegionSupportEnabled` (runtime/SDK minimums, frameless HWND behaviour), GTK CSD behaviour, and whether host-drawn caption controls are required; then tier the options.'),
],
['nodeIntegration / contextIsolation:false / webSecurity:false / allowRunningInsecureContent / enableBlinkFeatures / experimentalFeatures (privilege-escalating; fail loudly)','offscreen rendering on system webviews (no OSR) — draw.io export window uses it: tracked ✘ with a fix-it','BrowserView (deprecated) beyond a Tier-3 mapping note'],
['TouchBar (11 classes, macOS) until a corpus app needs it','JumpList/Thumbar/Task structures (Windows) until a corpus app needs it','multi-view (View/WebContentsView tree) — Tier 3'],
['Window-bound role lifecycle (KEL-75 T4) interaction with window close','Parent/modal semantics on each engine (Zettlr modals; draw.io hidden export child)','Window-state persistence (`WindowStatePersistence`) mapping'])

# ---------------- F03 webcontents navigation ----------------
unit('F03','compat(webContents): navigation event vocabulary, navigation policy, window-open handler, executeJavaScript, preload registration, print/devtools','Tier 1',
"""## Scope
34 entities / 381 members: `WebContents` (195), `WebFrameMain`, `NavigationHistory`, `Debugger`, `webFrame` (renderer), `webContents` module, input-event and print structures, `sharedTexture`/offscreen structures (never). Live today: no WebContents facade; keld-wv `WebEngine` = create/navigate/eval(fire-and-forget)/bounds/devtools/destroy; the only navigation observable is a page-load-finished event; Windows denies popups and guards permission requests; the KEL-142 macOS bridge supplies the isolated-world injection seam and a navigation generation counter.

## Corpus demand (resolved)
`will-navigate` + unconditional `preventDefault` and `setWindowOpenHandler` (both apps; Zettlr deny-all, draw.io allows only `about:blank` with `overrideBrowserWindowOptions` after an `openExternal` side effect); `webContents.send` (Zettlr 49 / draw.io 9); `did-finish-load`; `loadURL`/`loadFile`; awaited `executeJavaScript` (draw.io 5+); zoom; `printToPDF`/`print`; `openDevTools`; `render-process-gone`; `destroyed`; `before-input-event` + `pasteAndMatchStyle` (draw.io). Zero demand for NavigationHistory, Debugger, offscreen (except draw.io's export window), sharedTexture, WebFrameMain frame-tree APIs.

## Maturity ladder
- L0: `webContents` facade exists with typed errors; never-list rows published.
- L1: `loadURL/loadFile`, `did-finish-load`, `send`, `executeJavaScript` work for quick-start and draw.io on macOS.
- L2: ordered navigation vocabulary, will-navigate veto semantics (guard ∧ app), window-open handler default, destroyed semantics pass pinned conformance entries on each engine or carry an explicit per-engine ▲.
- L3: corpus apps' navigation workflows pass under `keld dev`.

## Linear owners consumed
KEL-79 (origin/resource/navigation/popup policy), KEL-132 (media/GPU), KEL-142 (isolated world, generation counter), KEL-135 (profile), KEL-80 (bounded host→renderer delivery), SCV codec owner (open — see F03-D4).

## Design facts fixed by research (two refuters)
- Split ownership: keld-wv delivers a small engine-neutral navigation signal set (provisional-start, commit, same-document change, dom-content-loaded, finish, fail{code}) per backend; Electron's event vocabulary is synthesised once above it (facade/keld-compat), keyed by `(WebviewId, navigation generation)`. One generation owner is required (two counters exist today: bridge vs guard) — decision F04-A4.
- Navigation policy is guard-first, app-hook deny-only: the app's `will-navigate`/`will-frame-navigate` hook is invoked for every page-initiated cross-document navigation, the guard decision is computed independently, outcome = guard ∧ app; programmatic `loadURL` bypasses the app hook but not the guard.
- `setWindowOpenHandler`: the handler is always invoked (draw.io's has side effects); unrecognised returns are deny; default without handler is deny-with-diagnostic (▲ or `windowOpenHandler` quirk, chosen in the PR); `allow` requires synchronous host window minting inside the engine delegate.
- `executeJavaScript` needs an `EvalCallback` result envelope on `WebEngine::eval` and a structured-clone-compatible codec; the SCV codec has no owner yet (F03-D4 open).
- Preload runs in a dedicated app content world (third world), not the trusted KEL-142 world — panel contested decision; F07 owns the preload runtime.
- Devtools are dev-only; a host print broker serves `printToPDF`/`print`; `Debugger` is ✘.
""",
[
 T('F03-T1','conformance(webContents): pinned entries for navigation event order, will-navigate veto, window-open handler defaults, destroyed semantics and executeJavaScript results','conformance','Tier 1','L2',
   'Land red-until-implemented conformance entries citing the pinned `web-contents.md`: `did-start-loading → did-start-navigation → did-navigate → dom-ready → did-frame-finish-load → did-finish-load → did-stop-loading` for a top-level load; `will-navigate` not emitted for programmatic `loadURL`; `setWindowOpenHandler` unrecognised return = deny with console error; `executeJavaScript` resolves with the value / rejects with the thrown error; `render-process-gone` carries `details.reason`; `destroyed` ordering.',
   ['Every entry cites the doc sentence and an ordered observable; no timing comparisons','Negative controls exist for ordering and for the veto path','Entries are tagged per engine where Electron does not state the behaviour (observed-only cells can reach BEHAVIOR_MATCH only)'],
   ['Deleting did-navigate from the synthesised sequence fails the order entry'],
   ext=['KEL-237 manifest reuse','X01 oracle rules'],owner='KEL-237',gates=['none'],members=['did-start-loading','did-stop-loading','did-start-navigation','did-navigate','did-navigate-in-page','dom-ready','did-finish-load','did-fail-load','will-navigate','will-frame-navigate','setWindowOpenHandler','executeJavaScript','render-process-gone','destroyed','page-title-updated'],size='M',ready='ready-for-agent',
   current='No webContents conformance entries exist.',interfaces='KEL-237 manifest cells; fixtures with main.js + preload.cjs + index.html.',oos='Implementation.'),
 T('F03-T2','feat(webContents): engine-neutral navigation signals in keld-wv (macOS first) and Electron vocabulary synthesis keyed by one navigation generation','feature','Tier 1','L2',
   'Add the small navigation signal set to keld-wv (WKNavigationDelegate on macOS first: provisional start, commit, finish, fail, same-document change via the isolated-world reporter, DOMContentLoaded) and synthesise Electron events above it keyed by `(WebviewId, generation)`; `webContents.id` is the host webview id; `loadURL/loadFile` are host navigations that bypass the app hook but not the guard.',
   ['Top-level load emits the pinned ordered sequence on macOS','Same-document navigation (hash/pushState) emits `did-navigate-in-page` only','`webContents.id` is stable across navigations and host-minted','Windows/Linux lanes either pass the same entries or carry an explicit per-engine ▲'],
   ['Removing the commit signal fails the did-navigate entry'],
   blocked=['F03-T1','F02-T2','F04-A4'],ext=['KEL-142 generation counter','KEL-79 navigation policy'],owner='KEL-79 / KEL-142',gates=['public API'],members=['id','loadURL','loadFile','getURL','getTitle','isLoading','reload','stop','did-start-loading','did-stop-loading','did-navigate','did-navigate-in-page','dom-ready','did-finish-load','did-fail-load','page-title-updated'],size='L',ready='needs-spec',plat='macOS first',
   current='Only a page-load-finished observable exists.',interfaces='keld-wv navigation hooks (design review of the engine trait); facade webContents class; one generation owner.',oos='Guard navigation policy (F03-T3); window-open handler (F03-T4).'),
 T('F03-T3','feat(webContents): guard-first navigation policy with deny-only will-navigate/will-frame-navigate hooks (outcome = guard ∧ app)','feature','Tier 1','L2',
   'Evaluate every top-level/frame navigation against a generated per-window `web.navigate` allow-list (app bundle resources and the app origin implicit) before the engine commits (WK decidePolicyFor, WebView2 NavigationStarting, WebKitGTK decide-policy); invoke the app hook for every page-initiated cross-document navigation; deny when either denies; programmatic loads skip the app hook only.',
   ['A page-initiated navigation to a non-granted origin is cancelled before commit with `KELD-GUARD` deny text naming the manifest patch','draw.io/Zettlr unconditional `preventDefault` keeps the app on its page; `loadURL` by the app still works','Removing the guard check leaves the app hook alone — the negative test proves the guard denies independently'],
   ['Making the app hook able to allow a guard-denied navigation fails the "cannot widen" negative test'],
   blocked=['F03-T2'],ext=['KEL-79','arch 03 §2 windows.<w>.web grant block (new key web.navigate)'],owner='KEL-79 / KEL-102',gates=['permission model'],members=['will-navigate','will-frame-navigate','did-redirect-navigation','will-redirect'],size='M',ready='needs-spec',
   current='No navigation policy exists (wry defaults).',interfaces='keld-wv pre-commit policy hook; keld-guard `windows.<name>.web.navigate` key; facade hook invocation.',oos='Popup/window-open (F03-T4).'),
 T('F03-T4','feat(webContents): setWindowOpenHandler — always invoke the handler, deny by default with diagnostic, allow via synchronous host window minting','feature','Tier 1','L2',
   'Install per-engine new-window hooks; always call the app handler (side effects matter); treat unrecognised returns as deny; without a handler deny with a diagnostic (documented ▲ against Electron allow-by-default, or a `windowOpenHandler` quirk); on `allow`, mint a child window synchronously inside the engine delegate with `overrideBrowserWindowOptions` and `channels: []` unless granted.',
   ['draw.io `about:blank` allow path creates a child window with the override options; `openExternal` side effect still runs','Zettlr deny-all handler produces no window and no engine popup','A minted child webview starts with no channel grants (KELD-GUARD003 on first `el:` call)'],
   ['Removing the handler invocation when the host would deny anyway fails the side-effect entry'],
   blocked=['F03-T2','F02-T2'],ext=['KEL-79 popup policy','KEL-168 WebView2 popup guard'],owner='KEL-79',gates=['permission model'],members=['setWindowOpenHandler','WindowOpenHandlerResponse','did-create-window'],size='M',ready='needs-spec',
   current='Windows denies all popups at the engine; macOS/Linux rely on wry defaults.',interfaces='keld-wv new-window hooks on three engines; host child-window minting; facade handler.',oos='<webview> (F07, Tier 3).'),
 T('F03-T5','feat(webContents): executeJavaScript/insertCSS with a host-owned result envelope over WebEngine::eval','feature','Tier 1','L1',
   'Extend the engine eval seam with a completion callback and wrap app code in one host-owned async envelope producing `{ok,value}` / `{ok:false,name,message,stack}` serialised with the shared structured-clone-compatible codec (owner per F03-D4); reject when the page navigates before completion; bound result size.',
   ['`await executeJavaScript("1+1")` resolves 2 on all three engines; a thrown error rejects with name/message','A result above the bound rejects with a typed error naming the limit','Navigation during execution rejects with the stale-generation error'],
   ['Returning a fire-and-forget undefined fails the resolve entry'],
   blocked=['F03-T2','F03-D4'],owner='KEL-142',gates=['public API'],members=['executeJavaScript','executeJavaScriptInIsolatedWorld','insertCSS','removeInsertedCSS'],size='M',ready='needs-spec',
   current='eval is fire-and-forget on every live backend.',interfaces='keld-wv eval callback; codec; facade Promise mapping.',oos='webFrame renderer variants beyond the subset the preload shim exposes.'),
],
[
 D('F03-D4','Who owns the structured-clone-compatible value codec (arch 02 §5 SCV) used by executeJavaScript, ipc and webContents.send?','grilling',
   'Arch 02 §5 names a postcard-encoded SCV codec covering Electron\'s value domain, but no spec, owner or Linear issue exists; KEL-98 is explicitly echo-only; KEL-80 does not own it. Decide the owner and the minimum v0 domain (JSON domain + Date/Map/Set/Error/TypedArray refs → bulk lane) before F03-T5, F04-T3 and F04-T4 can be specified.'),
 D('F03-D6','How are print/printToPDF/devtools mapped per engine while release policy stays closed?','research',
   'Host print broker candidates: WKWebView createPDF (macOS 11+), WebView2 PrintToPdf to a host temp path, WebKitGTK print operation (unverified); Zettlr prints from the renderer (`window.print()`), draw.io from main. Devtools are dev-only; whether a public WKWebView API can present the Web Inspector is unverified. Settle with receipts and record ✔/▲/✘ per engine.'),
],
['sharedTexture / OffscreenSharedTexture / offscreen rendering (no OSR on system webviews)','Debugger (CDP) in production webviews','NavigationHistory restore from serialised state beyond ▲ (zero corpus demand)'],
['WebFrameMain frame-tree APIs beyond senderFrame (zero demand)'],
['`before-input-event` + `pasteAndMatchStyle` engine hooks (draw.io) — new engine hooks not derivable from navigation signals','Zoom API mapping per engine (`zoomFactor`, `setVisualZoomLevelLimits`)','draw.io export window (offscreen + capturePage): replacement path to be specified'])
json.dump(DRAFTS,open('drafts_part1.json','w'),indent=1); print('part1 units:',list(DRAFTS), 'tickets:',sum(len(u['tickets']) for u in DRAFTS.values()))
