import json, subprocess, time
n=json.load(open('publish_state.json')); REPO='gyldlab/keld'
PROV="> Generated by an AI agent (Claude Code, Opus 5.5) on behalf of @0monish, 2026-10-07, under the map's execution doctrine. Statements are labelled FACT / INFERENCE / ASSUMPTION / UNKNOWN; nothing here authorizes implementation."
def gh(args, inp=None):
    p=subprocess.run(['gh','api']+args,input=inp,capture_output=True,text=True)
    if p.returncode: raise SystemExit(p.stderr[:400])
    return json.loads(p.stdout) if p.stdout.strip() else {}
def r(k): return f"#{n[k]['number']}"
D7=f"""{PROV}

Parent map: #391 · Unit: X06 (program sequencing) · Wayfinder type: `grilling` · Status: **open — owner action required** · Milestone: `first-proof`

## Question

Which Linear issue owns each repo-writing Electron-compat slice while the KELD Linear workspace cannot create new issues?

## Why it blocks the first proof

Every ticket that writes to the Keld repository (conformance entries included) needs a Linear owner before its first edit: `docs/agents/workflow.md` requires an `## Agent claim` on the Linear issue, earliest `createdAt` wins, and root `AGENTS.md` requires an approved spec plus a Linear (KELD) issue for features. Decision, research and prototype tickets on this map write only to scratchpads and the research branch, so they are not blocked.

## Facts

- FACT (Linear, fetched 2026-10-07): the workspace holds 275 non-archived issues (KEL-1…KEL-274 with gaps, plus GYL-1…GYL-4).
- FACT (linear.app/pricing, fetched 2026-10-07): the Free plan includes "250 issues".
- FACT (linear.app/docs/team-issue-limit, fetched 2026-10-07): "Archived issues do not count toward this limit", and "issues continue to count toward the limit until they are archived, even after they are completed". That page describes the per-team limit.
- FACT (KEL-127 comment `d833440d`, 2026-10-05): Linear refused a create with "You've exceeded the free issue limit for this workspace".
- FACT: KEL-237's scope is the currently implemented lifecycle slice; its non-goals exclude compatibility-surface expansion. No live Linear issue owns the `@keld/electron` facade beyond lifecycle (KEL-72 and KEL-142 are Done).

## Inferences and unknowns

- INFERENCE: the 250 free-plan figure counts non-archived issues the same way; the pricing page itself does not say so.
- INFERENCE: nothing was archived since 2026-10-05, so creation is still refused. Not tested, because testing requires a create.
- So creating N new issues requires archiving at least 25 + N issues first.

## Alternatives

| Option | Cost | New invariant | Invariant at risk |
|---|---|---|---|
| A. Upgrade the workspace or start a trial | Billing; owner action | none | none |
| B. Archive completed issues (for example Done Phase 0–1 research and RFC issues) | Owner action; reversible by unarchiving | Archive policy for Done issues | none (archived issues stay readable) |
| C. Interim routing: claim each repo-writing slice on the existing live Linear owner of the surface it changes (KEL-75, 78, 79, 80, 102, 135, 139–144; KEL-237 only within its lifecycle scope) | Owner-less slices wait (BrowserWindow facade, new conformance families, migrate analyzer) | One owner per surface, unchanged | none |
| D. Let a GitHub issue satisfy the Linear-owner gate | Changes the claim protocol in `docs/agents/workflow.md` | Two trackers arbitrate claims | Single claim arbiter; requires the `.agents/instructions.md` change protocol |

## Recommendation

Adopt **C** now (adopted under the user's delegation; it is the existing workflow applied as written). The owner then chooses **B** or **A** for the owner-less slices. B is recommended: it is free and reversible. After freeing at least 33 slots, create one Linear issue per first-proof epic slice (about eight), not one per GitHub ticket, and link each epic here.

**Rejected:** D, because it changes the agent workflow without the instruction-change protocol and splits claim arbitration.

**Falsifier:** a KELD issue create succeeds today. Then the cap is gone; close this ticket and create the slice issues.

## The one owner question

Archive old Done issues (B), or upgrade the workspace (A)?

**First completion check:** a new KELD issue can be created, and each first-proof epic on #391 links its Linear issue.
"""
D8=f"""{PROV}

Parent map: #391 · Unit: X06 (program sequencing) · Wayfinder type: `research` · Status: **resolved**

## Question

What is the exact entry condition for Electron-compat work against the product spine (KEL-139–144), given what has actually landed?

## Resolution

1. **Start now, no predecessor:** decision, research and prototype tickets on this map, and anything that writes only to scratchpads or the research branch (all three gating experiments: {r('PANEL-P1')}, {r('PANEL-P2')}, {r('PANEL-P3')}).
2. **Repo-landing work** starts only with a live Linear owner claim (see {r('MAP')} decision "Linear owner for repo-writing Electron-compat slices"), a conformance entry first, and an approved spec where the slice adds behaviour.
3. **Spine artifacts consumed:** KEL-142 (Done) is the artifact every compat lane consumes. Facades that dispatch a guarded broker additionally consume the landed KEL-102/T3 route. That is an inference until the draw.io boot/authority trace ({r('PANEL-P3')}) confirms which brokers the workflow touches.
4. **KEL-102/T3 is passed and landed, so it is no longer a blocker.** Facts: terminal artifact comment `cde25f5e` on KEL-102, landed `66ccbbc` (PR #357), landed-main CI `37313738834`. KEL-140 reports its predecessor gate satisfied and remains unclaimed (KEL-102 comment `264b4e6c`). KEL-140's Linear blockers KEL-142, KEL-130, KEL-139 and KEL-133 are closed (Linear, fetched 2026-10-07).
5. The stale T3 checkbox in the KEL-102 spec and the related "not landed" sentences are already owned by KEL-102 comment `fd9d0b91`: a decided docs-only reconciliation PR, blocked on disk space on the owner's Mac. Not duplicated here.

**Evidence:** Linear KEL-102 comments `cde25f5e`, `264b4e6c`, `fd9d0b91`; KEL-140 relations; `git merge-base --is-ancestor 66ccbbc origin/main` (true at `8678c0d1`).

**Falsifier:** a KEL-102/T3 revert on `origin/main`, or a KEL-140 relation that re-blocks it.
"""
out={}
for key,title,body,labels,close in [
  ('X06-D7','Linear owner for repo-writing Electron-compat slices while the KELD workspace is at its free issue cap',D7,['electron-compat','wayfinder:grilling','milestone:first-proof','ready-for-human'],False),
  ('X06-D8','Entry condition for Electron-compat work against the product spine (KEL-102/T3 landed; repo writes need a Linear owner)',D8,['electron-compat','wayfinder:research','milestone:first-proof'],True)]:
    if key in n: print(key,'exists',n[key]); continue
    j=gh(['-X','POST',f'repos/{REPO}/issues','--input','-'],inp=json.dumps({'title':title,'body':body,'labels':labels,'type':'Task'}))
    n[key]={'number':j['number'],'id':j['id'],'node_id':j['node_id']}; json.dump(n,open('publish_state.json','w'),indent=1)
    gh(['-X','POST',f"repos/{REPO}/issues/391/sub_issues",'--input','-'],inp=json.dumps({'sub_issue_id':j['id']})); time.sleep(0.6)
    if close: gh(['-X','PATCH',f"repos/{REPO}/issues/{j['number']}",'--input','-'],inp=json.dumps({'state':'closed','state_reason':'completed'}))
    print('created',key,'#',j['number'],'closed' if close else 'open')
# correction comment on PANEL-D13 (closed decision): enumeration source for el: grants
c13=f"""{PROV}

## Correction to the evidence behind this decision (decision unchanged)

The map's kill-condition text said "draw.io's single rendererReq channel is enumerable". Re-checked directly in the pinned corpus clone (drawio-desktop `2edf9fb`), that is wrong:

- FACT: `src/main/electron.js` makes 27 `ipcMain.on`/`once`/`handle` registrations over **25 distinct channel literals** (for example `rendererReq`, `isModified-result`, `saveAndClose-result`, `export-finalize`, `app-load-finished`, `toggleSpellCheck`, `zoomIn`).
- FACT: the preload's exposed `sendMessage`/`listenOnce` forward a caller-chosen channel name to `ipcRenderer.send`/`once`.

Consequence: the enumerated `el:<channel>` grant this decision requires must be derived from the **main-side registrations** (all 25 are static string literals, so `keld migrate` can enumerate them), not from a single `rendererReq` channel. The decision itself (enumerated per-window grants, `el:*` refused) stands.
"""
num=n['PANEL-D13']['number']
gh(['-X','POST',f'repos/{REPO}/issues/{num}/comments','--input','-'],inp=json.dumps({'body':c13})); print('posted correction on PANEL-D13 #',num)
