/**
 * KEL-98 Unicode contract regressions. Literal postcard vectors are the oracle,
 * not bytes generated by the encoder being tested. The echo adapter is imported
 * from its real scaffold source so both consumers exercise one string decoder.
 */
import { describe, expect, test } from "bun:test";
import {
  decodeCallError,
  decodePostcardStringAt,
  errorFromErrFrame,
} from "./transport.ts";
import {
  decodeEchoResponse,
  encodeEchoRequest,
} from "../../../../crates/keld-cli/templates/hello/src/kipc.ts";

const validEchoVectors: ReadonlyArray<readonly [string, readonly number[]]> = [
  ["", [0x00, 0x00]],
  ["\uFEFFa", [0x04, 0xef, 0xbb, 0xbf, 0x61, 0x00]],
  ["\uFEFF\uFEFF", [0x06, 0xef, 0xbb, 0xbf, 0xef, 0xbb, 0xbf, 0x00]],
  ["\uFFFD", [0x03, 0xef, 0xbf, 0xbd, 0x00]],
  ["\u0000", [0x01, 0x00, 0x00]],
  ["\uD800\uDC00", [0x04, 0xf0, 0x90, 0x80, 0x80, 0x00]],
  ["\uDBFF\uDFFF", [0x04, 0xf4, 0x8f, 0xbf, 0xbf, 0x00]],
];

describe("postcard Unicode scalar identity", () => {
  for (const [message, vector] of validEchoVectors) {
    test(`preserves exact echo bytes for ${JSON.stringify(message)}`, () => {
      expect(Array.from(encodeEchoRequest({ message, count: 0 }))).toEqual([...vector]);
      expect(decodeEchoResponse(Uint8Array.from(vector))).toEqual({ message, count: 0 });
      // The final byte is count, not part of the postcard string.
      expect(decodePostcardStringAt(Uint8Array.from(vector), 0)).toEqual([
        message,
        vector.length - 1,
      ]);
    });
  }

  test("preserves a BOM at a nonzero field offset without consuming the next field", () => {
    const bytes = new Uint8Array([0x7f, 0x03, 0xef, 0xbb, 0xbf, 0x42]);
    expect(decodePostcardStringAt(bytes, 1)).toEqual(["\uFEFF", 5]);
    expect(bytes[5]).toBe(0x42);
  });

  test("a decoder error cannot poison the next independent valid decode", () => {
    expect(() => decodePostcardStringAt(new Uint8Array([0x01, 0xff]), 0))
      .toThrow("KELD-IPC-003");
    expect(decodePostcardStringAt(new Uint8Array([0x03, 0xef, 0xbb, 0xbf]), 0))
      .toEqual(["\uFEFF", 4]);
  });
});

describe("unrepresentable application strings", () => {
  for (const message of ["\uD800", "\uDFFF", "a\uD800b", "\uDC00\uD800", "\uD800\uD800"]) {
    test(`rejects unpaired UTF-16 instead of substituting U+FFFD: ${JSON.stringify(message)}`, () => {
      expect(() => encodeEchoRequest({ message, count: 0 })).toThrow("KELD-IPC-003");
    });
  }

  for (const message of [undefined, null, 42, {}, new String("x")]) {
    test(`rejects non-string input of type ${typeof message}`, () => {
      // Deliberately cross the static boundary as JS/untrusted input can.
      expect(() => encodeEchoRequest({ message: message as unknown as string, count: 0 }))
        .toThrow("KELD-IPC-003");
    });
  }

  test("rejects an object without invoking its toString conversion", () => {
    let coerced = false;
    const message = { toString() { coerced = true; return "x"; } };
    expect(() => encodeEchoRequest({ message: message as unknown as string, count: 0 }))
      .toThrow("KELD-IPC-003");
    expect(coerced).toBe(false);
  });
});

describe("malformed postcard strings", () => {
  const malformed = [
    [0x01, 0xff],
    [0x01, 0x80],
    [0x02, 0xc0, 0xaf],
    [0x03, 0xed, 0xa0, 0x80],
    [0x04, 0xf4, 0x90, 0x80, 0x80],
    [0x02, 0xe2, 0x82],
  ];
  for (const vector of malformed) {
    test(`classifies invalid UTF-8 ${vector.join(",")} as a codec error`, () => {
      expect(() => decodePostcardStringAt(Uint8Array.from(vector), 0))
        .toThrow("KELD-IPC-003");
      expect(() => decodeEchoResponse(Uint8Array.from([...vector, 0x00])))
        .toThrow("KELD-IPC-003");
    });
  }

  test("retains truncation, offset and trailing-byte rejection", () => {
    expect(() => decodePostcardStringAt(new Uint8Array([0x03, 0x61]), 0))
      .toThrow("KELD-IPC-003");
    expect(() => decodePostcardStringAt(new Uint8Array([0x00]), -1))
      .toThrow("KELD-IPC-003");
    expect(() => decodeEchoResponse(new Uint8Array([0x00, 0x00, 0x00])))
      .toThrow("KELD-IPC-003");
  });

  test("does not normalize a BOM-prefixed CallError code into a valid identifier", () => {
    // String length 8: U+FEFF followed by KELD-; then an empty message.
    const payload = new Uint8Array([0x08, 0xef, 0xbb, 0xbf, 0x4b, 0x45, 0x4c, 0x44, 0x2d, 0x00]);
    expect(() => decodeCallError(payload)).toThrow("KELD-IPC-003");
    expect(errorFromErrFrame(payload).message).toContain("KELD-IPC-005");
  });
});
