// @generated by packages/@keld/kipc/scripts/echo-codegen.ts.
// Source: crates/keld-ipc/src/echo.rs. Do not edit by hand.

export interface EchoRequest {
  message: string;
  /** Rust u32 domain: integer in 0..=4_294_967_295; runtime bounds stay in the postcard codec. */
  count: number;
}

export interface EchoResponse {
  message: string;
  /** Rust u32 domain: integer in 0..=4_294_967_295; runtime bounds stay in the postcard codec. */
  count: number;
}
