// @generated by packages/@keld/kipc/scripts/echo-codegen.ts.
// Source: crates/keld-native/src/fs.rs. Do not edit by hand.

import { MAX_FRAME_LEN, decodeVarint, encodeVarint, encodePostcardString, kipcError } from "../../kipc/src/transport.ts";

export type FsRequest =
  | { variant: "Read"; path: string }
  | { variant: "Write"; path: string; bytes: Uint8Array };

export type FsResponse =
  | { variant: "Read"; bytes: Uint8Array }
  | { variant: "Write" };

function encodeBytes(value: Uint8Array): Uint8Array {
  if (!(value instanceof Uint8Array)) throw kipcError("KELD-IPC-003", "FsRequest.bytes must be a Uint8Array");
  const length = encodeVarint(value.byteLength);
  if (length.length + value.byteLength > MAX_FRAME_LEN) throw kipcError("KELD-IPC-003", "FS payload exceeds MAX_FRAME_LEN");
  const encoded = new Uint8Array(length.length + value.byteLength);
  encoded.set(length);
  encoded.set(value, length.length);
  return encoded;
}

function joinPayload(parts: readonly Uint8Array[]): Uint8Array {
  const length = parts.reduce((total, part) => total + part.byteLength, 0);
  if (length > MAX_FRAME_LEN) throw kipcError("KELD-IPC-003", "FS payload exceeds MAX_FRAME_LEN");
  const payload = new Uint8Array(length);
  let offset = 0;
  for (const part of parts) { payload.set(part, offset); offset += part.byteLength; }
  return payload;
}

/** Encodes and snapshots a native request in Rust declaration order. */
export function encodeFsRequest(value: FsRequest): Uint8Array {
  if (!value || typeof value !== "object") throw kipcError("KELD-IPC-003", "FsRequest must be an object");
  switch (value.variant) {
    case "Read": return joinPayload([encodeVarint(0), encodePostcardString(value.path, "FsRequest.path")]);
    case "Write": return joinPayload([encodeVarint(1), encodePostcardString(value.path, "FsRequest.path"), encodeBytes(value.bytes)]);
    default: throw kipcError("KELD-IPC-003", "unknown FsRequest variant");
  }
}

/** Decodes an exact native response; returned content owns an independent copy. */
export function decodeFsResponse(payload: Uint8Array): FsResponse {
  if (!(payload instanceof Uint8Array)) throw kipcError("KELD-IPC-003", "FsResponse payload must be a Uint8Array");
  const [variant, afterVariant] = decodeVarint(payload, 0);
  let offset = afterVariant;
  let response: FsResponse;
  switch (variant) {
    case 0: {
      const [bytesLength, afterLength] = decodeVarint(payload, offset);
      const end = afterLength + bytesLength;
      if (end > payload.byteLength) throw kipcError("KELD-IPC-003", "FsResponse byte length does not match payload");
      const bytes = new Uint8Array(payload.subarray(afterLength, end));
      offset = end;
      response = { variant: "Read", bytes };
      break;
    }
    case 1: {
      response = { variant: "Write" };
      break;
    }
    default: throw kipcError("KELD-IPC-003", "unknown FsResponse variant");
  }
  if (offset !== payload.byteLength) throw kipcError("KELD-IPC-003", "trailing bytes after FsResponse");
  return response;
}
